### ISSUE TITLE
编辑自定义配置时，删除最后几行，闪退回程序主界面

### ISSUE THREAD

**Issue by chika0801** [2dust/v2rayNG#1371]
### 预期行为
正常删除第一行

### 实际行为
编辑自定义配置时，删除最后几行，闪退回程序主界面

### 复现方法
1.删除这最后几行
![IMG_20220211_074959](https://user-images.githubusercontent.com/88967758/153516823-707389ed-ebc9-4154-99c3-e7ea0c3fad3d.jpg)

2.光标在行首，再点一下删除，就会发生闪退
![IMG_20220211_075155](https://user-images.githubusercontent.com/88967758/153516874-8b390ce3-244c-4990-842c-d6057efae96d.jpg)

3.报错画面
![IMG_20220211_075106](https://user-images.githubusercontent.com/88967758/153517008-d6a35207-9c94-439e-8b1e-035494ff9fe7.jpg)

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
java.lang.IndexOutOfBoundsException: Index: 148, Size: 148
	at java.util.ArrayList.remove(ArrayList.java:503)
	at com.blacksquircle.ui.editorkit.utils.LinesCollection.remove(LinesCollection.kt:32)
	at com.blacksquircle.ui.editorkit.internal.LineNumbersEditText.removeLine(LineNumbersEditText.kt:263)
	at com.blacksquircle.ui.editorkit.internal.CodeSuggestsEditText.removeLine(CodeSuggestsEditText.kt:90)
	at com.blacksquircle.ui.editorkit.internal.LineNumbersEditText.replaceText(LineNumbersEditText.kt:246)
	at com.blacksquircle.ui.editorkit.internal.CodeSuggestsEditText.replaceText(CodeSuggestsEditText.kt:94)
	at com.blacksquircle.ui.editorkit.internal.LineNumbersEditText.doOnTextChanged(LineNumbersEditText.kt:175)
	at com.blacksquircle.ui.editorkit.internal.UndoRedoEditText.doOnTextChanged(UndoRedoEditText.kt:59)
	at com.blacksquircle.ui.editorkit.internal.SyntaxHighlightEditText.doOnTextChanged(SyntaxHighlightEditText.kt:104)
	at com.blacksquircle.ui.editorkit.internal.AutoIndentEditText.doOnTextChanged(AutoIndentEditText.kt:35)
	at com.blacksquircle.ui.editorkit.internal.CodeSuggestsEditText.doOnTextChanged(CodeSuggestsEditText.kt:51)
	at com.blacksquircle.ui.editorkit.internal.LineNumbersEditText$textWatcher$1.onTextChanged(LineNumbersEditText.kt:63)
	at android.widget.TextView.sendOnTextChanged(Unknown Source:19)
	at android.widget.TextView.handleTextChanged(Unknown Source:68)
	at android.widget.TextView$ChangeWatcher.onTextChanged(Unknown Source:2)
	at android.text.SpannableStringBuilder.sendTextChanged(Unknown Source:12)
	at android.text.SpannableStringBuilder.replace(Unknown Source:255)
	at android.text.SpannableStringBuilder.delete(Unknown Source:7)
	at android.text.SpannableStringBuilder.delete(Unknown Source:0)
	at android.text.method.BaseKeyListener.backspaceOrForwardDelete(Unknown Source:132)
	at android.text.method.BaseKeyListener.backspace(Unknown Source:6)
	at android.text.method.BaseKeyListener.onKeyDown(Unknown Source:10)
	at android.text.method.QwertyKeyListener.onKeyDown(Unknown Source:799)
	at android.text.method.TextKeyListener.onKeyDown(Unknown Source:4)
	at android.widget.TextView.doKeyDown(Unknown Source:333)
	at android.widget.TextView.onKeyDown(Unknown Source:1)
	at android.widget.AutoCompleteTextView.onKeyDown(Unknown Source:48)
	at com.blacksquircle.ui.editorkit.widget.TextProcessor.onKeyDown(TextProcessor.kt:80)
	at android.view.KeyEvent.dispatch(Unknown Source:65)
	at android.view.View.dispatchKeyEvent(Unknown Source:48)
	at android.view.ViewGroup.dispatchKeyEvent(Unknown Source:37)
	at android.view.ViewGroup.dispatchKeyEvent(Unknown Source:37)
	at android.view.ViewGroup.dispatchKeyEvent(Unknown Source:37)
	at android.widget.ScrollView.dispatchKeyEvent(Unknown Source:0)
	at android.view.ViewGroup.dispatchKeyEvent(Unknown Source:37)
	at android.view.ViewGroup.dispatchKeyEvent(Unknown Source:37)
	at android.view.ViewGroup.dispatchKeyEvent(Unknown Source:37)
	at android.view.ViewGroup.dispatchKeyEvent(Unknown Source:37)
	at android.view.ViewGroup.dispatchKeyEvent(Unknown Source:37)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(Unknown Source:22)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(Unknown Source:2)
	at android.app.Activity.dispatchKeyEvent(Unknown Source:27)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3068)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(Unknown Source:87)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(Unknown Source:22)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(Unknown Source:31)
	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:26)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4)
	at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
	at android.view.ViewRootImpl$AsyncInputStage.forward(Unknown Source:10)
	at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
	at android.view.ViewRootImpl$AsyncInputStage.apply(Unknown Source:7)
	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:34)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4)
	at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
	at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:34)
	at android.view.ViewRootImpl.deliverInputEvent(Unknown Source:165)
	at android.view.ViewRootImpl.doProcessInputEvents(Unknown Source:48)
	at android.view.ViewRootImpl.enqueueInputEvent(Unknown Source:165)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(Unknown Source:648)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(Unknown Source:15)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:77)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:306)

```
</details>

### 额外信息（可选）
版本1.6.30，先全选-复制-粘贴，最后几行前面有行号，无此现象
![IMG_20220211_075951](https://user-images.githubusercontent.com/88967758/153517395-a2c8fcd7-3609-4b61-a2f5-5bcc2ea77502.jpg)

**Comment by yuhan6665** [comment]
editorkit 是漂亮但是有一些 bug
麻烦 @2dust 更新依赖看看能不能修好

**Comment by 2dust** [comment]
[v2rayNG_1.6.31-rc_arm64-v8a.apk.zip](https://github.com/2dust/v2rayNG/files/8059551/v2rayNG_1.6.31-rc_arm64-v8a.apk.zip)

com.blacksquircle.ui:editorkit:2.1.1

**Comment by chika0801** [comment]
> [v2rayNG_1.6.31-rc_arm64-v8a.apk.zip](https://github.com/2dust/v2rayNG/files/8059551/v2rayNG_1.6.31-rc_arm64-v8a.apk.zip)
> 
> com.blacksquircle.ui:editorkit:2.1.1

miui 13 android 12 进程序后，点右下角图标连接，不能用。系统栏VPN图标没出来。

手动关闭也失败，只能后台关进程。再开也是点了连接，实际上没连。

**Comment by chika0801** [comment]
```
java.lang.RuntimeException: Unable to start service com.v2ray.ang.service.V2RayVpnService@3391712 with Intent { cmp=com.v2ray.ang/.service.V2RayVpnService }: java.lang.IllegalArgumentException: com.v2ray.ang: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.handleServiceArgs(Unknown Source:146)
	at android.app.ActivityThread.access$2100(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:671)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:309)
Caused by: java.lang.IllegalArgumentException: com.v2ray.ang: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(Unknown Source:73)
	at android.app.PendingIntent.getActivityAsUser(Unknown Source:18)
	at android.app.PendingIntent.getActivity(Unknown Source:23)
	at android.app.PendingIntent.getActivity(Unknown Source:1)
	at com.v2ray.ang.service.V2RayServiceManager.showNotification(V2RayServiceManager.kt:252)
	at com.v2ray.ang.service.V2RayServiceManager.startV2rayPoint(V2RayServiceManager.kt:153)
	at com.v2ray.ang.service.V2RayVpnService.onStartCommand(V2RayVpnService.kt:255)
	at android.app.ActivityThread.handleServiceArgs(Unknown Source:60)
	... 9 more
```

**Comment by 2dust** [comment]
@chika0801 不要点击运行和使用(因为targetsdk升级到31了)。
只验证自定义配置修改时是否已经正常？
如果还是不正常，说明最新的编辑器也没有修复bug，将回滚targetsdk到30
[v2rayNG_1.6.31-rc2_arm64-v8a.apk.zip](https://github.com/2dust/v2rayNG/files/8067598/v2rayNG_1.6.31-rc2_arm64-v8a.apk.zip)

**Comment by chika0801** [comment]
> @chika0801 不要点击运行和使用(因为targetsdk升级到31了)。 只验证自定义配置修改时是否已经正常？ 如果还是不正常，说明最新的编辑器也没有修复bug，将回滚targetsdk到30 [v2rayNG_1.6.31-rc2_arm64-v8a.apk.zip](https://github.com/2dust/v2rayNG/files/8067598/v2rayNG_1.6.31-rc2_arm64-v8a.apk.zip)

只验证自定义配置修改时是否已经正常？

没有修复。

现在的现象是，在任何一行，删除，光标删到行首位，再按一次删除，从编辑界面闪退到程序主界面。

**Comment by 2dust** [comment]
我们这边的测试机们无此问题，暂时无法解决
请用其他编辑器编辑后导入

**Comment by chika0801** [comment]
谢谢你。

**Comment by GeorgeRudd** [comment]
> > @chika0801 不要点击运行和使用(因为targetsdk升级到31了)。 只验证自定义配置修改时是否已经正常？ 如果还是不正常，说明最新的编辑器也没有修复bug，将回滚targetsdk到30 [v2rayNG_1.6.31-rc2_arm64-v8a.apk.zip](https://github.com/2dust/v2rayNG/files/8067598/v2rayNG_1.6.31-rc2_arm64-v8a.apk.zip)
> 
> 只验证自定义配置修改时是否已经正常？
> 
> 没有修复。
> 
> 现在的现象是，在任何一行，删除，光标删到行首位，再按一次删除，从编辑界面闪退到程序主界面。

我也遇到了同样的状况 光标删到行首位，再按一次删除，应用程序会崩溃 好几个版本都有问题 包括最新版 三星国行oneui4.1 安卓12

**Comment by chika0801** [comment]
> > > @chika0801 不要点击运行和使用(因为targetsdk升级到31了)。 只验证自定义配置修改时是否已经正常？ 如果还是不正常，说明最新的编辑器也没有修复bug，将回滚targetsdk到30 [v2rayNG_1.6.31-rc2_arm64-v8a.apk.zip](https://github.com/2dust/v2rayNG/files/8067598/v2rayNG_1.6.31-rc2_arm64-v8a.apk.zip)
> > 
> > 
> > 只验证自定义配置修改时是否已经正常？
> > 没有修复。
> > 现在的现象是，在任何一行，删除，光标删到行首位，再按一次删除，从编辑界面闪退到程序主界面。
> 
> 我也遇到了同样的状况 光标删到行首位，再按一次删除，应用程序会崩溃 好几个版本都有问题 包括最新版 三星国行oneui4.1 安卓12

不用管，作者也不修，自己编辑注意到就是。
