### ISSUE TITLE
v2rayNG crash issue

### ISSUE THREAD

**Issue by cuynu** [2dust/v2rayNG#1386]
When click button  : "Click me for more help" on Settings, Got v2rayNG has been stopped. Please fix it.
Version : 1.7.0

Here is my logcat get from v2rayNG
--------- beginning of main
02-21 18:15:40.412 I/com.v2ray.ang(10127): Settings ViewModel is cleared
02-21 18:15:46.537 E/com.v2ray.ang(10127): java.net.ConnectException: Failed to connect to /127.0.0.1:10809
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at com.v2ray.ang.ui.UserAssetActivity.downloadGeo(UserAssetActivity.kt:170)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at com.v2ray.ang.ui.UserAssetActivity.access$downloadGeo(UserAssetActivity.kt:38)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at com.v2ray.ang.ui.UserAssetActivity$downloadGeoFiles$1$1.invokeSuspend(UserAssetActivity.kt:141)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
02-21 18:15:46.537 E/com.v2ray.ang(10127): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
02-21 18:15:46.538 E/com.v2ray.ang(10127): java.net.ConnectException: Failed to connect to /127.0.0.1:10809
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at com.v2ray.ang.ui.UserAssetActivity.downloadGeo(UserAssetActivity.kt:170)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at com.v2ray.ang.ui.UserAssetActivity.access$downloadGeo(UserAssetActivity.kt:38)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at com.v2ray.ang.ui.UserAssetActivity$downloadGeoFiles$1$1.invokeSuspend(UserAssetActivity.kt:141)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
02-21 18:15:46.538 E/com.v2ray.ang(10127): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
02-21 18:16:01.112 D/AndroidRuntime(10127): Shutting down VM
--------- beginning of crash
02-21 18:16:01.112 E/AndroidRuntime(10127): FATAL EXCEPTION: main
02-21 18:16:01.112 E/AndroidRuntime(10127): Process: com.v2ray.ang, PID: 10127
02-21 18:16:01.112 E/AndroidRuntime(10127): java.lang.IllegalStateException: Could not find method onModeHelpClicked(View) in a parent or ancestor Context for android:onClick attribute defined on view class androidx.appcompat.widget.AppCompatButton
02-21 18:16:01.112 E/AndroidRuntime(10127): 	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.resolveMethod(AppCompatViewInflater.java:479)
02-21 18:16:01.112 E/AndroidRuntime(10127): 	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:437)
02-21 18:16:01.112 E/AndroidRuntime(10127): 	at android.view.View.performClick(View.java:7455)
02-21 18:16:01.112 E/AndroidRuntime(10127): 	at android.view.View.performClickInternal(View.java:7432)
02-21 18:16:01.112 E/AndroidRuntime(10127): 	at android.view.View.access$3600(View.java:810)
02-21 18:16:01.112 E/AndroidRuntime(10127): 	at android.view.View$PerformClick.run(View.java:28312)
02-21 18:16:01.112 E/AndroidRuntime(10127): 	at android.os.Handler.handleCallback(Handler.java:938)
02-21 18:16:01.112 E/AndroidRuntime(10127): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-21 18:16:01.112 E/AndroidRuntime(10127): 	at android.os.Looper.loop(Looper.java:223)
02-21 18:16:01.112 E/AndroidRuntime(10127): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
02-21 18:16:01.112 E/AndroidRuntime(10127): 	at java.lang.reflect.Method.invoke(Native Method)
02-21 18:16:01.112 E/AndroidRuntime(10127): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
02-21 18:16:01.112 E/AndroidRuntime(10127): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-21 18:16:01.408 E/com.v2ray.ang(10394): Not starting debugger since process cannot load the jdwp agent.
02-21 18:16:01.410 W/com.v2ray.ang(10394): Core platform API violation: Ljava/lang/reflect/Field;->accessFlags:I from Landroid/os/Build; using reflection
02-21 18:16:55.962 D/AndroidRuntime(10394): Shutting down VM
02-21 18:16:55.964 E/AndroidRuntime(10394): FATAL EXCEPTION: main
02-21 18:16:55.964 E/AndroidRuntime(10394): Process: com.v2ray.ang, PID: 10394
02-21 18:16:55.964 E/AndroidRuntime(10394): java.lang.IllegalStateException: Could not find method onModeHelpClicked(View) in a parent or ancestor Context for android:onClick attribute defined on view class androidx.appcompat.widget.AppCompatButton
02-21 18:16:55.964 E/AndroidRuntime(10394): 	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.resolveMethod(AppCompatViewInflater.java:479)
02-21 18:16:55.964 E/AndroidRuntime(10394): 	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:437)
02-21 18:16:55.964 E/AndroidRuntime(10394): 	at android.view.View.performClick(View.java:7455)
02-21 18:16:55.964 E/AndroidRuntime(10394): 	at android.view.View.performClickInternal(View.java:7432)
02-21 18:16:55.964 E/AndroidRuntime(10394): 	at android.view.View.access$3600(View.java:810)
02-21 18:16:55.964 E/AndroidRuntime(10394): 	at android.view.View$PerformClick.run(View.java:28312)
02-21 18:16:55.964 E/AndroidRuntime(10394): 	at android.os.Handler.handleCallback(Handler.java:938)
02-21 18:16:55.964 E/AndroidRuntime(10394): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-21 18:16:55.964 E/AndroidRuntime(10394): 	at android.os.Looper.loop(Looper.java:223)
02-21 18:16:55.964 E/AndroidRuntime(10394): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
02-21 18:16:55.964 E/AndroidRuntime(10394): 	at java.lang.reflect.Method.invoke(Native Method)
02-21 18:16:55.964 E/AndroidRuntime(10394): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
02-21 18:16:55.964 E/AndroidRuntime(10394): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-21 18:16:58.470 E/com.v2ray.ang(10746): Not starting debugger since process cannot load the jdwp agent.
02-21 18:16:58.475 W/com.v2ray.ang(10746): Core platform API violation: Ljava/lang/reflect/Field;->accessFlags:I from Landroid/os/Build; using reflection

**Comment by cuynu** [comment]
Bug fixed on 1.7.1.
