### ISSUE TITLE
两次不同的崩溃

### ISSUE THREAD

**Issue by macarthor** [2dust/v2rayNG#1904]
v2rayng在后台运行，vpn模式，正在观看ytb视频时v2rayng崩溃

crash 1：
```
12-18 20:23:49.452 E/AndroidRuntime(30963): FATAL EXCEPTION: main
12-18 20:23:49.452 E/AndroidRuntime(30963): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 30963
12-18 20:23:49.452 E/AndroidRuntime(30963): android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1845a4 u0 com.v2ray.ang/.service.V2RayVpnService}
12-18 20:23:49.452 E/AndroidRuntime(30963): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2053)
12-18 20:23:49.452 E/AndroidRuntime(30963): 	at android.app.ActivityThread.access$2800(ActivityThread.java:253)
12-18 20:23:49.452 E/AndroidRuntime(30963): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2282)
12-18 20:23:49.452 E/AndroidRuntime(30963): 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-18 20:23:49.452 E/AndroidRuntime(30963): 	at android.os.Looper.loopOnce(Looper.java:233)
12-18 20:23:49.452 E/AndroidRuntime(30963): 	at android.os.Looper.loop(Looper.java:344)
12-18 20:23:49.452 E/AndroidRuntime(30963): 	at android.app.ActivityThread.main(ActivityThread.java:8191)
12-18 20:23:49.452 E/AndroidRuntime(30963): 	at java.lang.reflect.Method.invoke(Native Method)
12-18 20:23:49.452 E/AndroidRuntime(30963): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
12-18 20:23:49.452 E/AndroidRuntime(30963): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
12-18 21:29:22.278 E/AndroidRuntime(28298): FATAL EXCEPTION: main
12-18 21:29:22.278 E/AndroidRuntime(28298): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 28298
12-18 21:29:22.278 E/AndroidRuntime(28298): android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{41d90ac u0 com.v2ray.ang/.service.V2RayVpnService}
12-18 21:29:22.278 E/AndroidRuntime(28298): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2053)
12-18 21:29:22.278 E/AndroidRuntime(28298): 	at android.app.ActivityThread.access$2800(ActivityThread.java:253)
12-18 21:29:22.278 E/AndroidRuntime(28298): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2282)
12-18 21:29:22.278 E/AndroidRuntime(28298): 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-18 21:29:22.278 E/AndroidRuntime(28298): 	at android.os.Looper.loopOnce(Looper.java:233)
12-18 21:29:22.278 E/AndroidRuntime(28298): 	at android.os.Looper.loop(Looper.java:344)
12-18 21:29:22.278 E/AndroidRuntime(28298): 	at android.app.ActivityThread.main(ActivityThread.java:8191)
12-18 21:29:22.278 E/AndroidRuntime(28298): 	at java.lang.reflect.Method.invoke(Native Method)
12-18 21:29:22.278 E/AndroidRuntime(28298): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
12-18 21:29:22.278 E/AndroidRuntime(28298): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

crash 2：
```
01-08 14:31:08.414 E/com.v2ray.ang( 5019): Unknown bits set in runtime_flags: 0x40000000
01-08 14:31:08.420 E/com.v2ray.ang( 5019): Not starting debugger since process cannot load the jdwp agent.
01-08 14:31:08.508 E/com.v2ray.ang( 5019): Loaded layer handle (12270633143962980309) for layer /my_product/lib64/libcolorx-loader.so
01-08 14:31:08.508 E/com.v2ray.ang( 5019): Looking for entrypoint ColorX_Check
01-08 14:31:08.509 E/com.v2ray.ang( 5019): Found ColorX_Check for /my_product/lib64/libcolorx-loader.so
01-08 14:31:08.511 E/com.v2ray.ang( 5019): Check failed
01-08 14:31:09.098 E/com.v2ray.ang( 5019): ofbOpen failed with error=No such file or directory
01-08 14:31:09.098 E/com.v2ray.ang( 5019): sysOpen failed with error=No such file or directory
01-08 14:31:09.104 W/com.v2ray.ang( 5019): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.jorgecastilloprz.progressarc.ProgressArcView.stop()' on a null object reference
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at com.github.jorgecastilloprz.FABProgressCircle.hide(FABProgressCircle.java:166)
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at com.v2ray.ang.ui.MainActivity.hideCircle$lambda-16(MainActivity.kt:612)
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at com.v2ray.ang.ui.MainActivity.$r8$lambda$hDiKl7atAtG-1sj3dZQE0kDBUnQ(Unknown Source:0)
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at com.v2ray.ang.ui.MainActivity$$ExternalSyntheticLambda3.call(Unknown Source:4)
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:224)
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at android.os.Handler.handleCallback(Handler.java:938)
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at android.os.Looper.loopOnce(Looper.java:233)
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at android.os.Looper.loop(Looper.java:344)
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at android.app.ActivityThread.main(ActivityThread.java:8191)
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at java.lang.reflect.Method.invoke(Native Method)
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
01-08 14:31:09.104 W/com.v2ray.ang( 5019): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

**Comment by macarthor** [comment]
PS：两次都是通过back键finish了activity之后，观看youtube app时崩溃的，v2rayng不在前台，UI被杀掉了，只剩service了
