### ISSUE TITLE
Geosite下载失败

### ISSUE THREAD

**Issue by tanwov** [2dust/v2rayNG#2197]
### 预期行为
正常下载更新geosite.dat 和 geoip.dat

### 实际行为
下载失败

### 复现方法
GeoSite资源文件点击下载按钮

### 问题原因
AppConfig.kt 常量
```
const val geoUrl = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/";
```
应该更新为
```
const val geoUrl = "https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/";
```

**Comment by 2dust** [comment]
经过测试，没有问题
你需要开启代理后下载

**Comment by tanwov** [comment]
找到原因了，我的HTTP代理端口设置为0了
```
04-19 09:02:53.175 E/com.v2ray.ang(20981): java.net.SocketException: No route to 127.0.0.1:0; port is out of range
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:170)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.v2ray.ang.ui.UserAssetActivity.downloadGeo(UserAssetActivity.kt:170)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.v2ray.ang.ui.UserAssetActivity.access$downloadGeo(UserAssetActivity.kt:38)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at com.v2ray.ang.ui.UserAssetActivity$downloadGeoFiles$1$1.invokeSuspend(UserAssetActivity.kt:141)
04-19 09:02:53.175 E/com.v2ray.ang(20981): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

结合代码，是要用到http代理
```
val httpPort = Utils.parseInt(settingsStorage?.decodeString(AppConfig.PREF_HTTP_PORT), AppConfig.PORT_HTTP.toInt())
```
