### ISSUE TITLE
Crash when start VPN

### ISSUE THREAD

**Issue by vardidze-rostom** [2dust/v2rayNG#2597]
Hello comrades, i have installed v2rayNG on my Android 14 (GrapheneOS) and the app doesn't work correctly. Here is logs:
type: crash
osVersion: google/bluejay/bluejay:14/UP1A.231105.003/2023110700:user/release-keys
package: com.v2ray.ang:2000516
process: com.v2ray.ang:RunSoLibV2RayDaemon
processUptime: 30025 + 366 ms

android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{99a4c4e u0 com.v2ray.ang/.service.V2RayVpnService}
 at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2111)
 at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2082)
 at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2376)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:205)
 at android.os.Looper.loop(Looper.java:294)
 at android.app.ActivityThread.main(ActivityThread.java:8199)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
 at com.android.internal.os.ExecInit.main(ExecInit.java:49)
 at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
 at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

The program can't  start VPN service after add Vless config.

I have tested on Android Studio Emulator with 14 Android and get the same issue.  

Here is my Vless config:

vless://f1426cd0-671a-4632-b50f-88ddff2c970e@example.com:23683?type=tcp&security=reality&fp=android&pbk=qiXvWJ6oJt12cBE82S59dbKgzdYNLNCIyeNpb3jlTHM&sni=youtube.com&flow=xtls-rprx-vision&sid=33c9eb59&spx=%2F#rostom%20mobile-p36kf7s9

**Comment by vardidze-rostom** [comment]
Here is another logs:
--------- beginning of crash
11-10 23:41:34.134 E/AndroidRuntime(24404): FATAL EXCEPTION: main
11-10 23:41:34.134 E/AndroidRuntime(24404): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 24404
11-10 23:41:34.134 E/AndroidRuntime(24404): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{99a4c4e u0 com.v2ray.ang/.service.V2RayVpnService}
11-10 23:41:34.134 E/AndroidRuntime(24404): 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2111)
11-10 23:41:34.134 E/AndroidRuntime(24404): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2082)
11-10 23:41:34.134 E/AndroidRuntime(24404): 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
11-10 23:41:34.134 E/AndroidRuntime(24404): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2376)
11-10 23:41:34.134 E/AndroidRuntime(24404): 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-10 23:41:34.134 E/AndroidRuntime(24404): 	at android.os.Looper.loopOnce(Looper.java:205)
11-10 23:41:34.134 E/AndroidRuntime(24404): 	at android.os.Looper.loop(Looper.java:294)
11-10 23:41:34.134 E/AndroidRuntime(24404): 	at android.app.ActivityThread.main(ActivityThread.java:8199)
11-10 23:41:34.134 E/AndroidRuntime(24404): 	at java.lang.reflect.Method.invoke(Native Method)
11-10 23:41:34.134 E/AndroidRuntime(24404): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
11-10 23:41:34.134 E/AndroidRuntime(24404): 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
11-10 23:41:34.134 E/AndroidRuntime(24404): 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-10 23:41:34.134 E/AndroidRuntime(24404): 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
11-10 23:43:37.742 E/AndroidRuntime(25231): FATAL EXCEPTION: main
11-10 23:43:37.742 E/AndroidRuntime(25231): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 25231
11-10 23:43:37.742 E/AndroidRuntime(25231): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b80dc34 u0 com.v2ray.ang/.service.V2RayVpnService}
11-10 23:43:37.742 E/AndroidRuntime(25231): 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2111)
11-10 23:43:37.742 E/AndroidRuntime(25231): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2082)
11-10 23:43:37.742 E/AndroidRuntime(25231): 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
11-10 23:43:37.742 E/AndroidRuntime(25231): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2376)
11-10 23:43:37.742 E/AndroidRuntime(25231): 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-10 23:43:37.742 E/AndroidRuntime(25231): 	at android.os.Looper.loopOnce(Looper.java:205)
11-10 23:43:37.742 E/AndroidRuntime(25231): 	at android.os.Looper.loop(Looper.java:294)
11-10 23:43:37.742 E/AndroidRuntime(25231): 	at android.app.ActivityThread.main(ActivityThread.java:8199)
11-10 23:43:37.742 E/AndroidRuntime(25231): 	at java.lang.reflect.Method.invoke(Native Method)
11-10 23:43:37.742 E/AndroidRuntime(25231): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
11-10 23:43:37.742 E/AndroidRuntime(25231): 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
11-10 23:43:37.742 E/AndroidRuntime(25231): 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-10 23:43:37.742 E/AndroidRuntime(25231): 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
--------- beginning of main
11-11 06:03:10.819 I/com.v2ray.ang(30315): Using CollectorTypeCC GC.
11-11 06:03:10.824 E/com.v2ray.ang(30315): Not starting debugger since process cannot load the jdwp agent.
11-11 06:03:11.030 D/AndroidRuntime(30315): >>>>>> START com.android.internal.os.RuntimeInit uid 10214 <<<<<<
11-11 06:03:11.027 W/com.v2ray.ang(30315): type=1400 audit(0.0:44882): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=339 scontext=u:r:untrusted_app_32:s0:c214,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=com.v2ray.ang
11-11 06:03:11.048 I/AndroidRuntime(30315): Using default boot image
11-11 06:03:11.048 I/AndroidRuntime(30315): Leaving lock profiling enabled
11-11 06:03:11.051 W/com.v2ray.ang(30315): ART APEX data files are untrusted.
11-11 06:03:11.051 I/com.v2ray.ang(30315): Using CollectorTypeCC GC.
11-11 06:03:11.047 W/com.v2ray.ang(30315): type=1400 audit(0.0:44883): avc:  denied  { read } for  name="u:object_r:odsign_prop:s0" dev="tmpfs" ino=262 scontext=u:r:untrusted_app_32:s0:c214,c256,c512,c768 tcontext=u:object_r:odsign_prop:s0 tclass=file permissive=0 app=com.v2ray.ang
11-11 06:03:11.047 W/com.v2ray.ang(30315): type=1400 audit(0.0:44884): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=339 scontext=u:r:untrusted_app_32:s0:c214,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=com.v2ray.ang
11-11 06:03:11.047 W/com.v2ray.ang(30315): type=1400 audit(0.0:44885): avc:  denied  { getattr } for  path="/apex/apex-info-list.xml" dev="tmpfs" ino=79 scontext=u:r:untrusted_app_32:s0:c214,c256,c512,c768 tcontext=u:object_r:apex_info_file:s0 tclass=file permissive=0 app=com.v2ray.ang
11-11 06:03:11.059 W/com.v2ray.ang(30315): type=1400 audit(0.0:44886): avc:  denied  { lock } for  path="/system/framework/arm64/boot.art" dev="dm-10" ino=1445 scontext=u:r:untrusted_app_32:s0:c214,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.v2ray.ang
11-11 06:03:11.063 W/com.v2ray.ang(30315): type=1400 audit(0.0:44887): avc:  denied  { lock } for  path="/system/framework/arm64/boot-core-libart.art" dev="dm-10" ino=1391 scontext=u:r:untrusted_app_32:s0:c214,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.v2ray.ang
11-11 06:03:11.063 W/com.v2ray.ang(30315): type=1400 audit(0.0:44888): avc:  denied  { lock } for  path="/system/framework/arm64/boot-okhttp.art" dev="dm-10" ino=1427 scontext=u:r:untrusted_app_32:s0:c214,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.v2ray.ang
11-11 06:03:11.063 W/com.v2ray.ang(30315): type=1400 audit(0.0:44889): avc:  denied  { lock } for  path="/system/framework/arm64/boot-bouncycastle.art" dev="dm-10" ino=1379 scontext=u:r:untrusted_app_32:s0:c214,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.v2ray.ang
11-11 06:03:11.133 D/com.v2ray.ang(30315): Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
11-11 06:03:11.133 D/com.v2ray.ang(30315): I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt72l.dat
11-11 06:03:11.158 D/AndroidRuntime(30315): Calling main entry com.android.internal.os.ExecInit
11-11 06:03:11.180 E/com.v2ray.ang(30315): Unable to find pattern file or unable to map it for am
