### ISSUE TITLE
能发布一个正式的release，包含最新的Xray-Core版本(>=1.8.4)嘛

### ISSUE THREAD

**Issue by xiaoyxue** [2dust/v2rayNG#2654]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
V2rayNG 1.8.5 无法连接新建的vmess节点，server系统是Ubuntu 20.04 Gen2
V2rayN 也一样，但是升级Xray-Core之后就可以
目前Xray-Core 1.8.4已经是Release状态，可否发布一个正式版包含这个

### 实际行为
描述实际发生了什么

### 复现方法
1.  Xray-Core 1.8.1 无法连接
2.  Xray-Core 升级到最新可以连接

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
2023-11-29 09:46:50.0724-DEBUG    at System.Net.HttpWebRequest.GetResponse()
   at v2rayN.Handler.DownloadHandle.GetRealPingTime(String url, IWebProxy webProxy, Int32 downloadTimeout, Int32& responseTime)
2023-11-29 09:46:50.0724-ERROR System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
2023-11-29 09:46:53.2592-DEBUG The SSL connection could not be established, see inner exception.,The SSL connection could not be established, see inner exception.
2023-11-29 09:46:53.2592-DEBUG    at System.Net.HttpWebRequest.GetResponse()
   at v2rayN.Handler.DownloadHandle.GetRealPingTime(String url, IWebProxy webProxy, Int32 downloadTimeout, Int32& responseTime)
2023-11-29 09:46:53.2592-ERROR System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
2023-11-29 09:47:39.9562-INFO UpdateTaskRunSubscription
2023-11-29 09:48:30.8550-DEBUG The SSL connection could not be established, see inner exception.,The SSL connection could not be established, see inner exception.
2023-11-29 09:48:30.8550-DEBUG    at System.Net.HttpWebRequest.GetResponse()
   at v2rayN.Handler.DownloadHandle.GetRealPingTime(String url, IWebProxy webProxy, Int32 downloadTimeout, Int32& responseTime)
2023-11-29 09:48:30.8550-ERROR System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
2023-11-29 09:48:39.9574-INFO UpdateTaskRunGeo
2023-11-29 09:48:41.9384-DEBUG The operation has timed out.,The operation has timed out.
2023-11-29 09:48:41.9384-DEBUG    at System.Net.HttpWebRequest.GetResponse()
   at v2rayN.Handler.DownloadHandle.GetRealPingTime(String url, IWebProxy webProxy, Int32 downloadTimeout, Int32& responseTime)
```
</details>

### 环境信息
Server 为 Ubuntu 20.04 Gen2, Ubuntu 22.04 都不行

**Comment by xiaoyxue** [comment]
或者增加功能可以自行升级内核版本
