### ISSUE TITLE
最新的1.8.12的版本停止运行

### ISSUE THREAD

**Issue by yujantime** [2dust/v2rayNG#2663]
点击通知栏快捷开关后v2rayNG运行不成功，并且有报错，1.8.11版本无此问题
### 日志信息
<details>
--------- beginning of main
12-04 18:24:01.977 D/AndroidRuntime(27734): Shutting down VM
--------- beginning of crash
12-04 18:24:01.977 E/AndroidRuntime(27734): FATAL EXCEPTION: main
12-04 18:24:01.977 E/AndroidRuntime(27734): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 27734
12-04 18:24:01.977 E/AndroidRuntime(27734): java.lang.SecurityException: com.v2ray.ang: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.os.Parcel.createException(Parcel.java:3041)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.os.Parcel.readException(Parcel.java:3024)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.os.Parcel.readException(Parcel.java:2966)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6193)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1863)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1803)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1791)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:766)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at com.v2ray.ang.service.QSTileService.onStartListening(QSTileService.kt:39)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.service.quicksettings.TileService$H.handleMessage(TileService.java:488)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.os.Looper.loopOnce(Looper.java:224)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.os.Looper.loop(Looper.java:318)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.app.ActivityThread.main(ActivityThread.java:8744)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at java.lang.reflect.Method.invoke(Native Method)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
12-04 18:24:01.977 E/AndroidRuntime(27734): Caused by: android.os.RemoteException: Remote stack trace:
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14683)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12174)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3173)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2859)
12-04 18:24:01.977 E/AndroidRuntime(27734): 	at android.os.Binder.execTransactInternal(Binder.java:1346)
12-04 18:24:01.977 E/AndroidRuntime(27734): 
</details>

### 环境信息
Xiaomi HyperOS 1.0.23(Android 14)

**Comment by marierose147** [comment]
1.8.12，会经常停止运行。三星s23国行系统，android14 oneui6.0。

**Comment by 09960827245** [comment]
در تاریخ دوشنبه ۴ دسامبر ۲۰۲۳،‏ ۲:۱۵ ب.ظ yujantime ***@***.***>
نوشت:

**Comment by popboyhsf** [comment]
1.8.12，会经常停止运行。三星国行系统，android14 oneui6.0。

**Comment by 2dust** [comment]
@popboyhsf @marierose147  有log提供否？

**Comment by 2dust** [comment]
[v2rayNG_1.8.12-test_arm64-v8a.zip](https://github.com/2dust/v2rayNG/files/13554097/v2rayNG_1.8.12-test_arm64-v8a.zip)

@yujantime 试一试

**Comment by popboyhsf** [comment]
> @popboyhsf @marierose147 有日志提供否？

2023-12-05 10:45:44.196 19497-19497 AndroidRuntime          com.v2ray.ang:RunSoLibV2RayDaemon    E  FATAL EXCEPTION: main
                                                                                                    Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 19497
                                                                                                    java.lang.SecurityException: com.v2ray.ang: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3053)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3036)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2978)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6137)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1914)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1854)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1842)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
                                                                                                    	at com.v2ray.ang.service.QSTileService.onStartListening(QSTileService.kt:39)
                                                                                                    	at android.service.quicksettings.TileService$H.handleMessage(TileService.java:797)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8913)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:16597)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:11530)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2928)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3196)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1375)

**Comment by yujantime** [comment]
> [v2rayNG_1.8.12-test_arm64-v8a.zip](https://github.com/2dust/v2rayNG/files/13554097/v2rayNG_1.8.12-test_arm64-v8a.zip)
> 
> @yujantime 试一试

还是报错
--------- beginning of main
12-05 12:49:39.327 D/AndroidRuntime(26046): Shutting down VM
--------- beginning of crash
12-05 12:49:39.328 E/AndroidRuntime(26046): FATAL EXCEPTION: main
12-05 12:49:39.328 E/AndroidRuntime(26046): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 26046
12-05 12:49:39.328 E/AndroidRuntime(26046): java.lang.SecurityException: com.v2ray.ang: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.os.Parcel.createException(Parcel.java:3041)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.os.Parcel.readException(Parcel.java:3024)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.os.Parcel.readException(Parcel.java:2966)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6193)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1863)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1803)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1791)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:766)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at com.v2ray.ang.service.QSTileService.onStartListening(QSTileService.kt:39)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.service.quicksettings.TileService$H.handleMessage(TileService.java:488)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.os.Looper.loopOnce(Looper.java:224)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.os.Looper.loop(Looper.java:318)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.app.ActivityThread.main(ActivityThread.java:8744)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at java.lang.reflect.Method.invoke(Native Method)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
12-05 12:49:39.328 E/AndroidRuntime(26046): Caused by: android.os.RemoteException: Remote stack trace:
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14683)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12174)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3173)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2859)
12-05 12:49:39.328 E/AndroidRuntime(26046): 	at android.os.Binder.execTransactInternal(Binder.java:1346)
12-05 12:49:39.328 E/AndroidRuntime(26046): 
12-05 12:49:40.412 D/AndroidRuntime(26073): Shutting down VM
12-05 12:49:40.412 E/AndroidRuntime(26073): FATAL EXCEPTION: main
12-05 12:49:40.412 E/AndroidRuntime(26073): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 26073
12-05 12:49:40.412 E/AndroidRuntime(26073): java.lang.SecurityException: com.v2ray.ang: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
12-05 12:49:40.412 E/AndroidRuntime(26073): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
12-05 12:49:40.412 E/AndroidRuntime(26073): 	at android.os.Parcel.createException(Parcel.java:3041)
12-05 12:49:40.412 E/AndroidRuntime(26073): 	at android.os.Parcel.readException(Parcel.java:3024)
12-05 12:49:40.412 E/AndroidRuntime(26073): 	at android.os.Parcel.readException(Parcel.java:2966)
12-05 12:49:40.412 E/AndroidRuntime(26073): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6193)
12-05 12:49:40.412 E/AndroidRuntime(26073): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1863)
12-05 12:49:40.412 E/AndroidRuntime(26073): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1803)
12-05 12:49:40.412 E/AndroidRuntime(26073): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1791)
12-05 12:49:40.412 E/AndroidRuntime(26073): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:766)
12-05 12:49:40.412 E/AndroidRuntime(26073): 	at com.v2ray.ang.service.QSTileService.onStartListening(QSTileService.kt:39)
12-05 12:49:40.412 E/AndroidRuntime(26073): 	at android.service.quicksettings.TileService$H.ha

**Comment by marierose147** [comment]
昨晚play商店从1.8.11更新到1.8.12之后出现此问题。今天卸载在play商店重装了1.8.12之后，未出现崩溃问题，无法复现。

**Comment by yujantime** [comment]
![Screenshot_2023-12-05-14-19-42-478_com miui bugreport](https://github.com/2dust/v2rayNG/assets/75920402/03d2ceb7-f85a-4f19-abba-e75da806adbc)

**Comment by popboyhsf** [comment]
![image](https://github.com/2dust/v2rayNG/assets/8099380/ce7c34d1-f350-4dbe-9010-ddb70f07e64b)
实测发现 
如果在快捷访问面板加入本应用快捷图标 就会出问题 
如果去掉本应用快捷图标 就没问题了

**Comment by marierose147** [comment]
好像我这个也是和快捷开关相关，快捷栏加入开关之后，下拉快捷栏就会触发崩溃
[崩溃log.txt](https://github.com/2dust/v2rayNG/files/13556590/log.txt)

**Comment by 2dust** [comment]
[v2rayNG_1.8.12-test2_arm64-v8a.zip](https://github.com/2dust/v2rayNG/files/13557267/v2rayNG_1.8.12-test2_arm64-v8a.zip)

感谢各位
下载这个版本测试

**Comment by popboyhsf** [comment]
> [v2rayNG_1.8.12-test2_arm64-v8a.zip](https://github.com/2dust/v2rayNG/files/13557267/v2rayNG_1.8.12-test2_arm64-v8a.zip)
> 
> 感谢各位 下载这个版本测试

可以了
快捷访问面板加入本应用快捷图标 也可以正常开关了  不会崩溃了
辛苦大佬

**Comment by yujantime** [comment]
> [v2rayNG_1.8.12-test2_arm64-v8a.zip](https://github.com/2dust/v2rayNG/files/13557267/v2rayNG_1.8.12-test2_arm64-v8a.zip)
> 
> 感谢各位 下载这个版本测试

经测试，正常😄

**Comment by marierose147** [comment]
> [v2rayNG_1.8.12-test2_arm64-v8a.zip](https://github.com/2dust/v2rayNG/files/13557267/v2rayNG_1.8.12-test2_arm64-v8a.zip)
> 
> 感谢各位 下载这个版本测试

测试正常了，感谢

**Comment by opts98** [comment]
感谢，test2测试没问题，我就说怎么昨天更新了一直停止运行，原来不是个例，我是小米14 安卓版本14

**Comment by caikun-cc** [comment]
非常感谢大佬，许愿这个周末发新版😏
