### ISSUE TITLE
V2Ray and a local Ktor (Netty) server

### ISSUE THREAD

**Issue by mik-sh** [2dust/v2rayNG#2811]
### 预期行为
V2Ray works along with a local Ktor (Netty) server.

### 实际行为
V2Ray service crashes a couple of seconds after the start.

### 复现方法
I have an application that runs a Ktor server based on Netty. It works on 127.0.0.1:3777.
If I start V2Ray while the server is working, the VPN service crashes just after the start.
I noticed that V2Ray uses the address 127.0.0.1 and I tried to change my local server address but it didn't solve the problem.
Is it possible to run a local Ktor server along with the V2Ray VPN service?

### 日志信息
FATAL EXCEPTION: DefaultDispatcher-worker-4
                                         Process: RunSoLibV2RayDaemon, PID: 19564
                                         java.net.BindException: Address already in use
                                         	at sun.nio.ch.Net.bind0(Native Method)
                                         	at sun.nio.ch.Net.bind(Net.java:442)
                                         	at sun.nio.ch.Net.bind(Net.java:434)
                                         	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
                                         	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
                                         	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:143)
                                         	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
                                         	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
                                         	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600)
                                         	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579)
                                         	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
                                         	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
                                         	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
                                         	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
                                         	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
                                         	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
                                         	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
                                         	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
                                         	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                                         	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
                                         	at io.ktor.server.netty.EventLoopGroupProxy$Companion.$r8$lambda$XgnKz7L6tCWRUaIAa7SVURwtFE4(Unknown Source:0)
                                         	at io.ktor.server.netty.EventLoopGroupProxy$Companion$$ExternalSyntheticLambda1.run(Unknown Source:2)
                                         	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                                         	at java.lang.Thread.run(Thread.java:1012)
                                         	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@43252ef, Dispatchers.Default]

**Comment by mik-sh** [comment]
It was my fault. I started Ktor server in the App class. This led to the server trying to start again when the VPN service started.
