### ISSUE TITLE
无法导入V2rayNG自己导出到剪贴板的Wireguard配置

### ISSUE THREAD

**Issue by tianzhiya880** [2dust/v2rayNG#2813]
无法导入V2rayNG自己导出到剪贴板的Wireguard配置

### 预期行为
能够像其他类型的配置一样，导入V2rayNG自己导出到剪贴板的Wireguard配置

### 实际行为
导出Wireguard配置到剪贴版正常，但是从剪贴板导入时报错，提示“失败”

### 复现方法
1. 选择导出Wireguard配置到剪贴版
2. 选择从剪贴板导入配置

### 日志信息
<details>

```
--------- beginning of main
02-02 13:10:43.303 D/com.v2ray.ang(32515): SCREEN_OFF, stop querying stats
02-02 13:11:13.877 D/com.v2ray.ang(32515): SCREEN_ON, start querying stats
02-02 13:11:27.973 W/com.v2ray.ang( 2295): Cleared Reference was only reachable from finalizer (only reported once)
02-02 13:11:31.960 W/System.err( 2295): java.lang.NumberFormatException: For input string: "null"
02-02 13:11:31.960 W/System.err( 2295): 	at java.lang.Integer.parseInt(Integer.java:797)
02-02 13:11:31.960 W/System.err( 2295): 	at java.lang.Integer.parseInt(Integer.java:915)
02-02 13:11:31.960 W/System.err( 2295): 	at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:457)
02-02 13:11:31.960 W/System.err( 2295): 	at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:950)
02-02 13:11:31.960 W/System.err( 2295): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:418)
02-02 13:11:31.960 W/System.err( 2295): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig$default(MainActivity.kt:410)
02-02 13:11:31.960 W/System.err( 2295): 	at com.v2ray.ang.ui.MainActivity.importClipboard(MainActivity.kt:402)
02-02 13:11:31.960 W/System.err( 2295): 	at com.v2ray.ang.ui.MainActivity.onOptionsItemSelected(MainActivity.kt:233)
02-02 13:11:31.960 W/System.err( 2295): 	at android.app.Activity.onMenuItemSelected(Activity.java:4404)
02-02 13:11:31.960 W/System.err( 2295): 	at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:550)
02-02 13:11:31.960 W/System.err( 2295): 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:265)
02-02 13:11:31.960 W/System.err( 2295): 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
02-02 13:11:31.960 W/System.err( 2295): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:110)
02-02 13:11:31.960 W/System.err( 2295): 	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:66)
02-02 13:11:31.960 W/System.err( 2295): 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:225)
02-02 13:11:31.960 W/System.err( 2295): 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
02-02 13:11:31.960 W/System.err( 2295): 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
02-02 13:11:31.960 W/System.err( 2295): 	at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:91)
02-02 13:11:31.961 W/System.err( 2295): 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
02-02 13:11:31.961 W/System.err( 2295): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
02-02 13:11:31.961 W/System.err( 2295): 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
02-02 13:11:31.961 W/System.err( 2295): 	at android.widget.AdapterView.performItemClick(AdapterView.java:352)
02-02 13:11:31.961 W/System.err( 2295): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1235)
02-02 13:11:31.961 W/System.err( 2295): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3232)
02-02 13:11:31.961 W/System.err( 2295): 	at android.os.Handler.handleCallback(Handler.java:938)
02-02 13:11:31.961 W/System.err( 2295): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-02 13:11:31.961 W/System.err( 2295): 	at android.os.Looper.loopOnce(Looper.java:233)
02-02 13:11:31.961 W/System.err( 2295): 	at android.os.Looper.loop(Looper.java:344)
02-02 13:11:31.961 W/System.err( 2295): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
02-02 13:11:31.961 W/System.err( 2295): 	at java.lang.reflect.Method.invoke(Native Method)
02-02 13:11:31.961 W/System.err( 2295): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
02-02 13:11:31.961 W/System.err( 2295): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
02-02 13:11:31.961 I/com.v2ray.ang( 2295): Parse base64 standard failed java.lang.IllegalArgumentException: bad base-64
02-02 13:11:31.961 I/com.v2ray.ang( 2295): Parse base64 url safe failed java.lang.IllegalArgumentException: bad base-64
```
</details>

### 环境信息
手机：一加7pro
系统：氧OS 12.1
安卓版本：安卓12
处理器：骁龙855

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.8.15
