### ISSUE TITLE
V2rayNG在Harmony系统服务启动失败

### ISSUE THREAD

**Issue by jwtty** [2dust/v2rayNG#2980]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
服务启动成功，VPN可用

### 实际行为
显示服务启动失败

### 复现方法
1. HarmonyOS 4.0.0.165
2.
3.

### 日志信息
通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
04-04 22:33:25.018 E/AndroidRuntime(18566): FATAL EXCEPTION: main
04-04 22:33:25.018 E/AndroidRuntime(18566): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 18566
04-04 22:33:25.018 E/AndroidRuntime(18566): android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{cfe1f86 u0 com.v2ray.ang/.service.V2RayVpnService}
04-04 22:33:25.018 E/AndroidRuntime(18566): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2590)
04-04 22:33:25.018 E/AndroidRuntime(18566): 	at android.app.ActivityThread.access$4000(ActivityThread.java:313)
04-04 22:33:25.018 E/AndroidRuntime(18566): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3003)
04-04 22:33:25.018 E/AndroidRuntime(18566): 	at android.os.Handler.dispatchMessage(Handler.java:117)
04-04 22:33:25.018 E/AndroidRuntime(18566): 	at android.os.Looper.loopOnce(Looper.java:205)
04-04 22:33:25.018 E/AndroidRuntime(18566): 	at android.os.Looper.loop(Looper.java:293)
04-04 22:33:25.018 E/AndroidRuntime(18566): 	at android.app.ActivityThread.loopProcess(ActivityThread.java:9970)
04-04 22:33:25.018 E/AndroidRuntime(18566): 	at android.app.ActivityThread.main(ActivityThread.java:9959)
04-04 22:33:25.018 E/AndroidRuntime(18566): 	at java.lang.reflect.Method.invoke(Native Method)
04-04 22:33:25.018 E/AndroidRuntime(18566): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
04-04 22:33:25.018 E/AndroidRuntime(18566): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)
```
</details>

**Comment by jwtty** [comment]
See this issue marked as "Closed" "not planned", is this a known issue not going to be fixed?
