### ISSUE TITLE
Bug when importing empty/invalid custom config causing app to crash forever

### ISSUE THREAD

**Issue by imkatman** [2dust/v2rayNG#3168]
### Expected Behavior
1. Not to import empty/invalid configs
2. If it did, not causing any problem in app's functionality

### Actual Behavior
App crashes as soon as it launches and the only solution is to clear app's data

### Reproduction Method
1. Copy `{}` to clipboard
2. Launch the app
3. Press `+` button
4. Tap `Custom Config` menu item
5. Tap `Import custom config from Clipboard` option

### Log Information
```
--------- beginning of main
05-27 12:54:11.510  7647  7647 I com.v2ray.ang: Late-enabling -Xcheck:jni
05-27 12:54:11.538  7647  7647 I com.v2ray.ang: Using CollectorTypeCC GC.
05-27 12:54:11.540  7647  7647 W com.v2ray.ang: Unexpected CPU variant for x86: x86_64.
05-27 12:54:11.540  7647  7647 W com.v2ray.ang: Known variants: atom, sandybridge, silvermont, goldmont, goldmont-plus, tremont, kabylake, default
05-27 12:54:12.346  7647  7647 W com.v2ray.ang: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
05-27 12:54:12.347  7647  7647 W com.v2ray.ang: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
05-27 12:54:12.590  7647  7669 I com.v2ray.ang: Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geoip.dat
05-27 12:54:12.605  7647  7669 I com.v2ray.ang: Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geosite.dat
05-27 12:54:12.666  7647  7647 W com.v2ray.ang: JNI critical lock held for 23.643ms on Thread[1,tid=7647,Runnable,Thread*=0x77ddaaf7bf50,peer=0x7292c400,"main"]
```
App crashes here.

After relaunching it crashes again:
```
05-27 12:54:46.280  7719  7719 I com.v2ray.ang: Late-enabling -Xcheck:jni
05-27 12:54:46.306  7719  7719 I com.v2ray.ang: Using CollectorTypeCC GC.
05-27 12:54:46.307  7719  7719 W com.v2ray.ang: Unexpected CPU variant for x86: x86_64.
05-27 12:54:46.307  7719  7719 W com.v2ray.ang: Known variants: atom, sandybridge, silvermont, goldmont, goldmont-plus, tremont, kabylake, default
05-27 12:54:46.834  7719  7719 W com.v2ray.ang: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
05-27 12:54:46.834  7719  7719 W com.v2ray.ang: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
```

<details>

```
2024-05-27 12:54:47.159  7719-7719  AndroidRuntime          com.v2ray.ang                        E  FATAL EXCEPTION: main
                                                                                                    Process: com.v2ray.ang, PID: 7719
                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.lang.Iterable.iterator()' on a null object reference
                                                                                                    	at com.v2ray.ang.dto.V2rayConfig.getProxyOutbound(V2rayConfig.kt:521)
                                                                                                    	at com.v2ray.ang.dto.ServerConfig.getProxyOutbound(ServerConfig.kt:56)
                                                                                                    	at com.v2ray.ang.ui.MainRecyclerAdapter.onBindViewHolder(MainRecyclerAdapter.kt:64)
                                                                                                    	at com.v2ray.ang.ui.MainRecyclerAdapter.onBindViewHolder(MainRecyclerAdapter.kt:33)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7747)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
                                                                                                    	at android.view.View.layout(View.java:24421)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6440)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
                                                                                                    	at android.view.View.layout(View.java:24421)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6440)
                                                                                                    	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
                                                                                                    	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
                                                                                                    	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
                                                                                                    	at android.view.View.layout(View.java:24421)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6440)
                                                                                                    	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
                                                                                                    	at android.view.View.layout(View.java:24421)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6440)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
                                                                                                    	at android.view.View.layout(View.java:24421)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6440)
                                                                                                    	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
                                                                                                    	at android.view.View.layout(View.java:24421)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6440)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:24421)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6440)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
                                                                                                    	at android.view.View.layout(View.java:24421)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6440)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:24421)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6440)
2024-05-27 12:54:47.162  7719-7719  AndroidRuntime          com.v2ray.ang                        E  	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
                                                                                                    	at android.view.View.layout(View.java:24421)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6440)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at com.android.internal.policy.DecorView.onLayout(DecorView.java:789)
                                                                                                    	at android.view.View.layout(View.java:24421)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6440)
                                                                                                    	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4258)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3583)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:882)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
</details>

### Environmental information
Device: `Resizable emulator with api 34`
App Version: `1.8.25`
Branch: `Master`
Last Commit Revision Number: `2ddbe38781d9206f80278e17440ed07ef67b143d`

**Comment by imkatman** [comment]
The problem is in the line `116` of `MainViewModel`:
```
        config.fullConfig = Gson().fromJson(server, V2rayConfig::class.java)

```
It uses a Java function which returns a value of type `V2rayConfig` which has some not nullable values such as  `outbounds: ArrayList<OutboundBean>`, but since it is a Java function it assigns a null object to those not nullable values.

This will cause the `getProxyOutbound` function in `V2rayConfig` class to throw exception since it is calling forEach on a null object:

```
fun getProxyOutbound(): OutboundBean? {
        outbounds.forEach { outbound ->
            EConfigType.entries.forEach {
                if (outbound.protocol.equals(it.name, true)) {
                    return outbound
                }
            }
        }
        return null
    }
```
in the code above the `outbounds` object would be null and causes the exception

**Comment by imkatman** [comment]
if we check `outbounds` for not being null before using forEach, this can prevent crashing issue. like code below:
```
fun getProxyOutbound(): OutboundBean? {
        outbounds?.forEach { outbound ->
            EConfigType.entries.forEach {
                if (outbound.protocol.equals(it.name, true)) {
                    return outbound
                }
            }
        }
        return null
    }
```

 But there is another problem. If now we add another config which is actually valid, the relay delaying all configs won't work for that config either as it seems to be a array slicing problem in the core library:
 ```
 2024-05-27 16:58:54.967  4888-0     Go                      com.v2ray.ang                        E  panic: runtime error: slice bounds out of range [:5] with capacity 4
2024-05-27 16:58:54.967  4888-4919  libc                    com.v2ray.ang                        A  Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 4919 (pool-2-thread-2), pid 4888 (oLibV2RayDaemon)
 ```
