### ISSUE TITLE
节点全部超时无法使用

### ISSUE THREAD

**Issue by YaM4NeK0** [2dust/v2rayNG#3313]
节点真连接和Tcping全部显示-1ms

### 预期行为
不应该显示-1ms

### 实际行为
显示了

### 复现方法
1.更新订阅
2.重新测试
3.没有发生预期结果

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```--------- beginning of crash
07-11 08:26:33.145 E/AndroidRuntime(12170): FATAL EXCEPTION: main
07-11 08:26:33.145 E/AndroidRuntime(12170): Process: com.v2ray.ang, PID: 12170
07-11 08:26:33.145 E/AndroidRuntime(12170): java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionMainViewHolder{ee1294e position=18 id=-1, oldPos=18, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{83567fc VFED..... .......D 0,0-1344,2226 #7f0901b3 app:id/recycler_view}, adapter:com.v2ray.ang.ui.MainRecyclerAdapter@d543e85, layout:androidx.recyclerview.widget.LinearLayoutManager@7c954da, context:com.v2ray.ang.ui.MainActivity@12f383b
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6156)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6339)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4255)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4010)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2017)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:417)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1599)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at android.view.Choreographer.doCallbacks(Choreographer.java:1263)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at android.view.Choreographer.doFrame(Choreographer.java:1122)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1549)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at android.os.Handler.handleCallback(Handler.java:966)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at android.os.Handler.dispatchMessage(Handler.java:110)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at android.os.Looper.loopOnce(Looper.java:205)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at android.os.Looper.loop(Looper.java:293)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at android.app.ActivityThread.loopProcess(ActivityThread.java:9986)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at android.app.ActivityThread.main(ActivityThread.java:9975)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at java.lang.reflect.Method.invoke(Native Method)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
07-11 08:26:33.145 E/AndroidRuntime(12170): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)
--------- beginning of main
07-11 08:26:34.565 E/com.v2ray.ang(19598): Not starting debugger since process cannot load the jdwp agent.

</details>

### 环境信息

### 额外信息（可选）

**Comment by YaM4NeK0** [comment]
所以这个怎么解决呢
