### ISSUE TITLE
[Bug] Java.lang.SecurityException: Unable to start service Intent { cmp=com.v2ray.ang/.service.V2RayVpnService }

### ISSUE THREAD

**Issue by Amir-yazdanmanesh** [2dust/v2rayNG#3466]
I just found this bug. When I open v2Ray, it immediately closes. I don't know if it's related to my debug version or not, but it was working recently.

`  Process: com.v2ray.ang, PID: 1016
                                                                                                    java.lang.SecurityException: Unable to start service Intent { cmp=com.v2ray.ang/.service.V2RayVpnService }: Unable to launch app com.v2ray.ang/10370 for service Intent { cmp=com.v2ray.ang/.service.V2RayVpnService }: process is bad
                                                                                                    	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1954)
                                                                                                    	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1917)
                                                                                                    	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:841)
                                                                                                    	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:841)
                                                                                                    	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:841)
                                                                                                    	at com.v2ray.ang.service.V2RayServiceManager.startV2Ray(V2RayServiceManager.kt:82)
                                                                                                    	at com.v2ray.ang.ui.MainActivity.startV2Ray(MainActivity.kt:209)
                                                                                                    	at com.v2ray.ang.ui.MainActivity.onCreate$lambda$2(MainActivity.kt:97)
                                                                                                    	at com.v2ray.ang.ui.MainActivity.$r8$lambda$5_AhYbKjoA0eiKRx41ZZnUkXZWs(Unknown Source:0)
                                                                                                    	at com.v2ray.ang.ui.MainActivity$$ExternalSyntheticLambda8.onClick(D8$$SyntheticClass:0)
                                                                                                    	at android.view.View.performClick(View.java:7798)
                                                                                                    	at android.view.View.performClickInternal(View.java:7775)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:31222)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:224)
                                                                                                    	at android.os.Looper.loop(Looper.java:318)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8755)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)`

**Comment by codewithtamim** [comment]
The SecurityException occurs because the app lacks proper permissions or has incorrect foreground service implementation, preventing the V2RayVpnService from starting.
