### ISSUE TITLE
1.9.12 Bug

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#3883]
hello 
Version 1.9.12 crashes every few moments Even when the software is turned off
@2dust @CodeWithTamim 
![IMG_۲۰۲۴۱۱۰۵_۱۵۴۶۴۰](https://github.com/user-attachments/assets/ee94868d-d767-4746-8a4c-72f15c1dba3b)
![Screenshot_۲۰۲۴-۱۱-۰۵-۱۵-۴۷-۱۲-۸۲۸_com v2ray ang-edit](https://github.com/user-attachments/assets/14f18d93-6849-4b19-97c6-72cdd4d911b6)

**Comment by codewithtamim** [comment]
Logs

**Comment by codewithtamim** [comment]
Receiver issue, check the QSTileService

**Comment by ghost** [comment]
> Receiver issue, check the QSTileService

I had to downgrade to version 1.9.11

**Comment by 2dust** [comment]
```
    override fun onStopListening() {
        super.onStopListening()
        try {
            unregisterReceiver(mMsgReceive)
            mMsgReceive = null
        } catch (e: Exception) {
            Log.d(ANG_PACKAGE, e.toString())
        }
    }
```

**Comment by codewithtamim** [comment]
I have better solution

**Comment by X-Oracle** [comment]
It is v2rayNG notification tile,
When closing the notification drawer it crashs then restarts again on its own.

Was it helpful? Or you need the logs too

Temporary solution until the next update:
Remove v2rayNG tile from the notification drawer.

**Comment by woworz** [comment]
I had the same problem.When I shut down the service, the software crashes.
Screenshot:
![Screenshot_20241106_010222_Smart Manager](https://github.com/user-attachments/assets/279d2333-bc20-4d68-a7eb-204716eb6266)
logs:
```
--------- beginning of crash
11-06 01:04:33.544 E/AndroidRuntime( 1031): FATAL EXCEPTION: main
11-06 01:04:33.544 E/AndroidRuntime( 1031): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 1031
11-06 01:04:33.544 E/AndroidRuntime( 1031): java.lang.IllegalArgumentException: Receiver not registered: com.v2ray.ang.service.QSTileService$ReceiveMessageHandler@a2df207
11-06 01:04:33.544 E/AndroidRuntime( 1031): 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1770)
11-06 01:04:33.544 E/AndroidRuntime( 1031): 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1899)
11-06 01:04:33.544 E/AndroidRuntime( 1031): 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:829)
11-06 01:04:33.544 E/AndroidRuntime( 1031): 	at com.v2ray.ang.util.Utils$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
11-06 01:04:33.544 E/AndroidRuntime( 1031): 	at com.v2ray.ang.service.QSTileService.onStopListening(QSTileService.kt:59)
11-06 01:04:33.544 E/AndroidRuntime( 1031): 	at android.service.quicksettings.TileService$H.handleMessage(TileService.java:741)
11-06 01:04:33.544 E/AndroidRuntime( 1031): 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-06 01:04:33.544 E/AndroidRuntime( 1031): 	at android.os.Looper.loopOnce(Looper.java:226)
11-06 01:04:33.544 E/AndroidRuntime( 1031): 	at android.os.Looper.loop(Looper.java:313)
11-06 01:04:33.544 E/AndroidRuntime( 1031): 	at android.app.ActivityThread.main(ActivityThread.java:8762)
11-06 01:04:33.544 E/AndroidRuntime( 1031): 	at java.lang.reflect.Method.invoke(Native Method)
11-06 01:04:33.544 E/AndroidRuntime( 1031): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
11-06 01:04:33.544 E/AndroidRuntime( 1031): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

My phone model: SM-G9860
Android version: 13
