### ISSUE TITLE
Weired custom configs result in non-stopping crashes on opening the app

### ISSUE THREAD

**Issue by HoseanRC** [2dust/v2rayNG#3911]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
Pressing on the app icon should open the app and let me use it

### 实际行为
The app crashes immediately after opening without any notice

### 复现方法
I don't exactly know how this happened and what the config contained, bit I believe it was like so:
```json
"outbounds": [
    {
      "domainStrategy": "AsIs",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "192.168.1.60",
            "port": 2080,
            "users": []
          }
        ]
```
Just make the users array empty and wait long enough for the "custom config to socks" migrator to kick in

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: com.v2ray.ang, PID: 5267
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at com.v2ray.ang.handler.MigrateManager.migrate2ProfileSocks(MigrateManager.kt:110)
	at com.v2ray.ang.handler.MigrateManager.migrateServerConfig2ProfileSub(MigrateManager.kt:53)
	at com.v2ray.ang.handler.MigrateManager.migrateServerConfig2Profile(MigrateManager.kt:32)
	at com.v2ray.ang.ui.MainActivity$migrateLegacy$1.invokeSuspend(MainActivity.kt:181)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ae862fe, Dispatchers.IO]
```
</details>

### 环境信息
I'm connecting to a local server though a custom configuration that I made, and I think I messed up the users array that it just broke the whole app

### 额外信息（可选）
```
com.v2ray.ang.handler.MigrateManager.migrate2ProfileSocks(MigrateManager.kt:110)
```
This is why the crash has been happening. There is a .get(0) on the users array, which has no children. It should've been checking for the length of the array before getting that index or use a failsafe method of doing this (returning undefined if there is no 0 index)

**Comment by HoseanRC** [comment]
Just a note: I'm not Chinese, so I can't understand that (I literally circle searched everything I saw). Please talk in English...
