### ISSUE TITLE
升级安卓15后（HyperOS2）订阅链接更新失败Failed to connect to /127.0.0.1:10809和javax.net.ssl.SSLHandshakeException错误

### ISSUE THREAD

**Issue by Chenglukas** [2dust/v2rayNG#3930]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
已经确认暂时没有相同ISSUE

### 预期行为
描述你认为应该发生什么
1. 应该成功更新订阅

### 实际行为
描述实际发生了什么
1. 无法更新订阅，但是网页打开订阅然后手动复制内容使用UI的剪贴板导入可以正常导入

### 复现方法
1. 更新订阅必复现

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
1. 更新订阅失败的log
--------- beginning of main
11-13 08:45:31.294 D/com.v2ray.ang(29246): https://******/subscription/custom?token=d0360775f7294bf977258d4b2e97a232
11-13 08:45:31.295 W/System.err(29246): java.net.ConnectException: Failed to connect to /127.0.0.1:10809
11-13 08:45:31.295 W/System.err(29246): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
11-13 08:45:31.295 W/System.err(29246): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
11-13 08:45:31.295 W/System.err(29246): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
11-13 08:45:31.295 W/System.err(29246): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
11-13 08:45:31.295 W/System.err(29246): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
11-13 08:45:31.295 W/System.err(29246): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
11-13 08:45:31.295 W/System.err(29246): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
11-13 08:45:31.295 W/System.err(29246): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
11-13 08:45:31.295 W/System.err(29246): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
11-13 08:45:31.295 W/System.err(29246): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
11-13 08:45:31.295 W/System.err(29246): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
11-13 08:45:31.295 W/System.err(29246): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
11-13 08:45:31.295 W/System.err(29246): 	at com.v2ray.ang.util.Utils.getUrlContentWithCustomUserAgent(Utils.kt:379)
11-13 08:45:31.295 W/System.err(29246): 	at com.v2ray.ang.util.AngConfigManager.updateConfigViaSub(AngConfigManager.kt:366)
11-13 08:45:31.295 W/System.err(29246): 	at com.v2ray.ang.util.AngConfigManager.updateConfigViaSubAll(AngConfigManager.kt:338)
11-13 08:45:31.295 W/System.err(29246): 	at com.v2ray.ang.viewmodel.MainViewModel.updateConfigViaSubAll(MainViewModel.kt:156)
11-13 08:45:31.295 W/System.err(29246): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$1.invokeSuspend(MainActivity.kt:605)
11-13 08:45:31.295 W/System.err(29246): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-13 08:45:31.295 W/System.err(29246): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
11-13 08:45:31.295 W/System.err(29246): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
11-13 08:45:31.295 W/System.err(29246): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
11-13 08:45:31.295 W/System.err(29246): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
11-13 08:45:31.295 W/System.err(29246): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
11-13 08:45:31.295 W/System.err(29246): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
11-13 08:45:31.295 W/System.err(29246): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
11-13 08:45:31.429 W/System.err(29246): javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1127)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1082)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:869)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:740)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:705)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:896)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:236)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:218)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
11-13 08:45:31.429 W/System.err(29246): 	at com.v2ray.ang.util.Utils.getUrlContentWithCustomUserAgent(Utils.kt:379)
11-13 08:45:31.429 W/System.err(29246): 	at com.v2ray.ang.util.Utils.getUrlContentWithCustomUserAgent$default(Utils.kt:355)
11-13 08:45:31.429 W/System.err(29246): 	at com.v2ray.ang.util.AngConfigManager.updateConfigViaSub(AngConfigManager.kt:373)
11-13 08:45:31.429 W/System.err(29246): 	at com.v2ray.ang.util.AngConfigManager.updateConfigViaSubAll(AngConfigManager.kt:338)
11-13 08:45:31.429 W/System.err(29246): 	at com.v2ray.ang.viewmodel.MainViewModel.updateConfigViaSubAll(MainViewModel.kt:156)
11-13 08:45:31.429 W/System.err(29246): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$1.invokeSuspend(MainActivity.kt:605)
11-13 08:45:31.429 W/System.err(29246): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-13 08:45:31.429 W/System.err(29246): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
11-13 08:45:31.429 W/System.err(29246): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
11-13 08:45:31.429 W/System.err(29246): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
11-13 08:45:31.429 W/System.err(29246): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
11-13 08:45:31.429 W/System.err(29246): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
11-13 08:45:31.429 W/System.err(29246): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
11-13 08:45:31.429 W/System.err(29246): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
11-13 08:45:31.429 W/System.err(29246): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:656)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
11-13 08:45:31.429 W/System.err(29246): 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
11-13 08:45:31.429 W/System.err(29246): 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:261)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1631)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:570)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1088)
11-13 08:45:31.429 W/System.err(29246): 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1072)
11-13 08:45:31.429 W/System.err(29246): 	... 34 more
11-13 08:45:31.429 W/System.err(29246): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-13 08:45:31.429 W/System.err(29246): 	... 47 more

```
</details>

### 环境信息
安卓15（HyperOS2）
### 额外信息（可选）
补充一点，订阅服务器的地址的SSL证书是正常的

**Comment by 2dust** [comment]
更新订阅时会先通过代理更新，而后会直连更新
你开着代理更新下
