### ISSUE TITLE
v1.9.17 xhttp 无法启动，编辑闪退

### ISSUE THREAD

**Issue by limetw** [2dust/v2rayNG#3988]
### 预期行为
xhttp生效

### 实际行为
xhttp无法启动，进编辑界面闪退

### 复现方法
1.直接把splithttp修改为xhttp，保存闪退
2.重新填写xhttp必要配置信息，无法启动
3.重填的xhttp再次进入编辑界面，闪退

### 日志信息
<details>

java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:165)
	at com.v2ray.ang.util.JsonUtil.parseString(JsonUtil.kt:45)
	at com.v2ray.ang.ui.ServerActivity$onCreate$1.onItemSelected(ServerActivity.kt:224)
	at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
	at android.widget.AdapterView.access$300(AdapterView.java:55)
	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:910)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)

</details>

### 环境信息
原生14，MIUI14（android 12)
自定义配置xhttp是可以正常运行的

### 额外信息（可选）
Termux输入 logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main 无内容，小问题就不开电脑抓了。给的是/data/system/dropbox的log

如有可能，请添加downloadSettings实现上下分流功能 thx

**Comment by limetw** [comment]
11-20 00:10:55.366  8121  8121 I GoLog   : loading core config
11-20 00:10:55.367  8121  8168 I GoLog   : Preparing Domain: *:443
11-20 00:10:55.372  8121  8168 I GoLog   : Prepare Result:
11-20 00:10:55.372  8121  8168 I GoLog   :  Domain: *
11-20 00:10:55.372  8121  8168 I GoLog   :  Port: 443
11-20 00:10:55.372  8121  8168 I GoLog   :  IPs: [*]
11-20 00:10:55.485  8121  8121 I GoLog   : infra/conf/serial: failed to parse json config > infra/conf: Config: unknown transport protocol: xhttp
11-20 00:10:55.485  8121  8121 D com.v2ray.ang: go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: Config: unknown transport protocol: xhttp

6f2c96c 编辑界面闪退已修复，但是启动失败

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.9.18
