### ISSUE TITLE
Can't save data after editing vpn configuration

### ISSUE THREAD

**Issue by helmiau** [2dust/v2rayNG#4074]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
After editing a configuration, check button (right-top button) should save the changes

### 实际行为
Can't save data after editing vpn configuration

### 复现方法
1. Edit any single config
2. Save the data
3. Error occured while data saving

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```

--------- beginning of main
11-29 21:39:28.012 D/AndroidRuntime(11734): Shutting down VM
--------- beginning of crash
11-29 21:39:28.012 E/AndroidRuntime(11734): FATAL EXCEPTION: main
11-29 21:39:28.012 E/AndroidRuntime(11734): Process: com.v2ray.ang, PID: 11734
11-29 21:39:28.012 E/AndroidRuntime(11734): java.lang.ArrayIndexOutOfBoundsException: length=7; index=-1
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at com.v2ray.ang.ui.ServerActivity.saveTls(ServerActivity.kt:561)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at com.v2ray.ang.ui.ServerActivity.saveServer(ServerActivity.kt:474)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at com.v2ray.ang.ui.ServerActivity.onOptionsItemSelected(ServerActivity.kt:642)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at android.app.Activity.onMenuItemSelected(Activity.java:4658)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.kt:477)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:265)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at androidx.appcompat.app.AppCompatDelegateImpl.onMenuItemSelected(AppCompatDelegateImpl.java:1235)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:833)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:157)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:974)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:620)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:155)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at android.view.View.performClick(View.java:7931)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at android.view.View.performClickInternal(View.java:7908)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at android.view.View$PerformClick.run(View.java:30992)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at android.os.Handler.handleCallback(Handler.java:959)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at android.os.Looper.loopOnce(Looper.java:232)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at android.os.Looper.loop(Looper.java:317)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at android.app.ActivityThread.main(ActivityThread.java:8601)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at java.lang.reflect.Method.invoke(Native Method)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
11-29 21:39:28.012 E/AndroidRuntime(11734): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
11-29 21:39:28.136 I/com.v2ray.ang(11872): Using CollectorTypeCC GC.
11-29 21:39:28.143 E/com.v2ray.ang(11872): Not starting debugger since process cannot load the jdwp agent.
11-29 21:39:28.146 W/com.v2ray.ang(11872): Core platform API violation: Ljava/lang/reflect/Field;->accessFlags:I from Landroid/os/Build; using reflection
11-29 21:39:41.226 D/AndroidRuntime(11872): Shutting down VM
11-29 21:39:41.226 E/AndroidRuntime(11872): FATAL EXCEPTION: main
11-29 21:39:41.226 E/AndroidRuntime(11872): Process: com.v2ray.ang, PID: 11872
11-29 21:39:41.226 E/AndroidRuntime(11872): java.lang.ArrayIndexOutOfBoundsException: length=7; index=-1
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at com.v2ray.ang.ui.ServerActivity.saveTls(ServerActivity.kt:561)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at com.v2ray.ang.ui.ServerActivity.saveServer(ServerActivity.kt:474)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at com.v2ray.ang.ui.ServerActivity.onOptionsItemSelected(ServerActivity.kt:642)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at android.app.Activity.onMenuItemSelected(Activity.java:4658)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.kt:477)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:265)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at androidx.appcompat.app.AppCompatDelegateImpl.onMenuItemSelected(AppCompatDelegateImpl.java:1235)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:833)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:157)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:984)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:974)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:620)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:155)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at android.view.View.performClick(View.java:7931)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at android.view.View.performClickInternal(View.java:7908)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at android.view.View$PerformClick.run(View.java:30992)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at android.os.Handler.handleCallback(Handler.java:959)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at android.os.Looper.loopOnce(Looper.java:232)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at android.os.Looper.loop(Looper.java:317)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at android.app.ActivityThread.main(ActivityThread.java:8601)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at java.lang.reflect.Method.invoke(Native Method)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
11-29 21:39:41.226 E/AndroidRuntime(11872): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
11-29 21:39:41.333 I/com.v2ray.ang(11974): Using CollectorTypeCC GC.
11-29 21:39:41.343 E/com.v2ray.ang(11974): Not starting debugger since process cannot load the jdwp agent.
11-29 21:39:41.345 W/com.v2ray.ang(11974): Core platform API violation: Ljava/lang/reflect/Field;->accessFlags:I from Landroid/os/Build; using reflection

```
</details>

### 额外信息（可选）
android info: Pixel 4a 5G (bramble), Android 14, ProjectMatrixx 10.8.1, not root
app info: 1.9.16 and 1.9.22

**Comment by 2dust** [comment]
check tls  sni   fingerPrint 
Take a screenshot of the configuration

**Comment by helmiau** [comment]
when tls is null, config can't be saved sometimes
when tls enabled with tls or reality, config can be saved

**Comment by 2dust** [comment]
Delete your current configuration, re-import and edit, is there any problem?

**Comment by helmiau** [comment]
i did, but the problem still occurs like attached logs before

**Comment by 2dust** [comment]
Please send the sharing link.

**Comment by helmiau** [comment]
idk what "sharing link" you mean, but here's v2rayNG backup file
[v2rayNG_2024-11-30-15-57-44.zip](https://github.com/user-attachments/files/17964813/v2rayNG_2024-11-30-15-57-44.zip)

and below is vmess sharing link
```
vmess://eyJhZGQiOiIxMDQuMjYuNy4xNzEiLCJhaWQiOiIwIiwiYWxwbiI6IiIsImZwIjoiIiwiaG9zdCI6Ind3dy5idWcuY29tIiwiaWQiOiI0MmJkMDZiMS0wOTdlLTQ2OWEtOGUxNC0xN2U4ZjIyOTc1MzMiLCJuZXQiOiJ3cyIsInBhdGgiOiIvP3R5cGVcdTAwM2R4cmF5LXZtZXNzLXdzLW50bHMiLCJwb3J0IjoiODAiLCJwcyI6ImlscGVkIHdpZmlpZCBnZ3ZwcyAyIiwic2N5IjoiYXV0byIsInNuaSI6IiIsInRscyI6IiIsInR5cGUiOiItLS0iLCJ2IjoiMiJ9
```

notes: this config is just a sample, it won't connected to the internet

**Comment by 2dust** [comment]
Unable to reproduce

**Comment by helmiau** [comment]
i noted "when tls is null, config can't be saved **sometimes**"
so the error will occurs "sometimes", maybe cause android version or something
