### ISSUE TITLE
已更新最新版本但仍无法使用，连接测试异常。

### ISSUE THREAD

**Issue by moyiyu** [2dust/v2rayNG#592]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。
--------- beginning of crash
09-08 00:36:50.563 E/AndroidRuntime( 7798): FATAL EXCEPTION: main
09-08 00:36:50.563 E/AndroidRuntime( 7798): Process: com.v2ray.ang, PID: 7798
09-08 00:36:50.563 E/AndroidRuntime( 7798): java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 20(offset:20).state:57 androidx.recyclerview.widget.RecyclerView{e29e5fb VFED..... .F...... 0,0-1080,1372 #7f090146 app:id/recycler_view}, adapter:com.v2ray.ang.ui.MainRecyclerAdapter@285b71b, layout:androidx.recyclerview.widget.LinearLayoutManager@a9b60b8, context:com.v2ray.ang.ui.MainActivity@f15af66
09-08 00:36:50.563 E/AndroidRuntime( 7798): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6183)
09-08 00:36:50.563 E/AndroidRuntime( 7798): 	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
09-08 00:36:50.563 E/AndroidRuntime( 7798): 	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
09-08 00:36:50.563 E/AndroidRuntime( 7798): 	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
09-08 00:36:50.563 E/AndroidRuntime( 7798): 	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
09-08 00:36:50.563 E/AndroidRuntime( 7798): 	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
09-08 00:36:50.563 E/AndroidRuntime( 7798): 	at android.os.Handler.handleCallback(Handler.java:808)
09-08 00:36:50.563 E/AndroidRuntime( 7798): 	at android.os.Handler.dispatchMessage(Handler.java:101)
09-08 00:36:50.563 E/AndroidRuntime( 7798): 	at android.os.Looper.loop(Looper.java:166)
09-08 00:36:50.563 E/AndroidRuntime( 7798): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
09-08 00:36:50.563 E/AndroidRuntime( 7798): 	at java.lang.reflect.Method.invoke(Native Method)
09-08 00:36:50.563 E/AndroidRuntime( 7798): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
09-08 00:36:50.563 E/AndroidRuntime( 7798): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
09-09 21:39:11.452 E/AndroidRuntime(13652): FATAL EXCEPTION: main
09-09 21:39:11.452 E/AndroidRuntime(13652): Process: com.v2ray.ang, PID: 13652
09-09 21:39:11.452 E/AndroidRuntime(13652): java.lang.RuntimeException: Unable to destroy activity {com.v2ray.ang/com.v2ray.ang.InappBuyActivity}: java.lang.IllegalArgumentException: Service not registered: com.v2ray.ang.util.IabHelper$1@9520f91
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5155)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5174)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at android.app.ActivityThread.-wrap6(Unknown Source:0)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at android.os.Handler.dispatchMessage(Handler.java:108)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at android.os.Looper.loop(Looper.java:166)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at java.lang.reflect.Method.invoke(Native Method)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
09-09 21:39:11.452 E/AndroidRuntime(13652): Caused by: java.lang.IllegalArgumentException: Service not registered: com.v2ray.ang.util.IabHelper$1@9520f91
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1654)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1818)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:697)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at com.v2ray.ang.util.IabHelper.dispose(IabHelper.java:291)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at com.v2ray.ang.InappBuyActivity.onDestroy(InappBuyActivity.java:335)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at android.app.Activity.performDestroy(Activity.java:7615)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1253)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5142)
09-09 21:39:11.452 E/AndroidRuntime(13652): 	... 9 more
--------- beginning of system
--------- beginning of main

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by moyiyu** [comment]
![Screenshot_20200909-215023](https://user-images.githubusercontent.com/71021921/92613509-ab2fe580-f280-11ea-9091-3003ba1541e8.jpg)
