### ISSUE TITLE
在oculus quest 2 上停止运行

### ISSUE THREAD

**Issue by yujantime** [2dust/v2rayNG#800]
点击右下角连接图标，在图标变绿后会停止运行。

<details>

```
12-12 21:13:27.701 E/AndroidRuntime( 4079): FATAL EXCEPTION: main
12-12 21:13:27.701 E/AndroidRuntime( 4079): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 4079
12-12 21:13:27.701 E/AndroidRuntime( 4079): java.lang.RuntimeException: Unable to start receiver com.v2ray.ang.receiver.WidgetProvider: java.lang.NullPointerException: manager must not be null
12-12 21:13:27.701 E/AndroidRuntime( 4079): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3806)
12-12 21:13:27.701 E/AndroidRuntime( 4079): 	at android.app.ActivityThread.access$1400(ActivityThread.java:226)
12-12 21:13:27.701 E/AndroidRuntime( 4079): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1879)
12-12 21:13:27.701 E/AndroidRuntime( 4079): 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-12 21:13:27.701 E/AndroidRuntime( 4079): 	at android.os.Looper.loop(Looper.java:214)
12-12 21:13:27.701 E/AndroidRuntime( 4079): 	at android.app.ActivityThread.main(ActivityThread.java:7387)
12-12 21:13:27.701 E/AndroidRuntime( 4079): 	at java.lang.reflect.Method.invoke(Native Method)
12-12 21:13:27.701 E/AndroidRuntime( 4079): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-12 21:13:27.701 E/AndroidRuntime( 4079): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
12-12 21:13:27.701 E/AndroidRuntime( 4079): Caused by: java.lang.NullPointerException: manager must not be null
12-12 21:13:27.701 E/AndroidRuntime( 4079): 	at com.v2ray.ang.receiver.WidgetProvider.onReceive(WidgetProvider.kt:56)
12-12 21:13:27.701 E/AndroidRuntime( 4079): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3797)
12-12 21:13:27.701 E/AndroidRuntime( 4079): 	... 8 more
```
</details>

### 系统信息
V23(Android 10)

**Comment by yuhan6665** [comment]
Thanks for your report, Will fix in next version

**Comment by yujantime** [comment]
最新1.5.4版本还是停止运行，错误信息都一模一样
```
12-19 19:18:50.411 E/AndroidRuntime( 5062): FATAL EXCEPTION: main
12-19 19:18:50.411 E/AndroidRuntime( 5062): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 5062
12-19 19:18:50.411 E/AndroidRuntime( 5062): java.lang.RuntimeException: Unable to start receiver com.v2ray.ang.receiver.WidgetProvider: java.lang.NullPointerException: manager must not be null
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3806)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.app.ActivityThread.access$1400(ActivityThread.java:226)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1879)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.os.Looper.loop(Looper.java:214)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.app.ActivityThread.main(ActivityThread.java:7387)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at java.lang.reflect.Method.invoke(Native Method)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
12-19 19:18:50.411 E/AndroidRuntime( 5062): Caused by: java.lang.NullPointerException: manager must not be null
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at com.v2ray.ang.receiver.WidgetProvider.onReceive(WidgetProvider.kt:56)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3797)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	... 8 more
```

**Comment by yujantime** [comment]
> Thanks for your report, Will fix in next version



> 感谢您的报告，将在下一版本中修复



> Thanks for your report, Will fix in next version

最新1.5.4版本还是停止运行，错误信息都一模一样
````
12-19 19:18:50.411 E/AndroidRuntime( 5062): FATAL EXCEPTION: main
12-19 19:18:50.411 E/AndroidRuntime( 5062): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 5062
12-19 19:18:50.411 E/AndroidRuntime( 5062): java.lang.RuntimeException: Unable to start receiver com.v2ray.ang.receiver.WidgetProvider: java.lang.NullPointerException: manager must not be null
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3806)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.app.ActivityThread.access$1400(ActivityThread.java:226)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1879)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.os.Looper.loop(Looper.java:214)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.app.ActivityThread.main(ActivityThread.java:7387)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at java.lang.reflect.Method.invoke(Native Method)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
12-19 19:18:50.411 E/AndroidRuntime( 5062): Caused by: java.lang.NullPointerException: manager must not be null
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at com.v2ray.ang.receiver.WidgetProvider.onReceive(WidgetProvider.kt:56)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3797)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	... 8 more
````

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.5.5
