### ISSUE TITLE
1.5.4 版本在 Oculus Quest 2 上还是会停止运行

### ISSUE THREAD

**Issue by yujantime** [2dust/v2rayNG#806]
点击右下角连接图标，在图标变绿后会停止运行。
shadowsocks-android 可以正常使用
错误信息和以前的一样。

### 日志信息
```
12-19 19:18:50.411 E/AndroidRuntime( 5062): FATAL EXCEPTION: main
12-19 19:18:50.411 E/AndroidRuntime( 5062): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 5062
12-19 19:18:50.411 E/AndroidRuntime( 5062): java.lang.RuntimeException: Unable to start receiver com.v2ray.ang.receiver.WidgetProvider: java.lang.NullPointerException: manager must not be null
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3806)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.app.ActivityThread.access$1400(ActivityThread.java:226)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1879)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.os.Looper.loop(Looper.java:214)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.app.ActivityThread.main(ActivityThread.java:7387)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at java.lang.reflect.Method.invoke(Native Method)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
12-19 19:18:50.411 E/AndroidRuntime( 5062): Caused by: java.lang.NullPointerException: manager must not be null
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at com.v2ray.ang.receiver.WidgetProvider.onReceive(WidgetProvider.kt:56)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3797)
12-19 19:18:50.411 E/AndroidRuntime( 5062): 	... 8 more
```
</details>

### 系统信息
v23.0.0.87.517(Android 10)

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.5.5

**Comment by yujantime** [comment]
> https://github.com/2dust/v2rayNG/releases/tag/1.5.5
1.5.5版本可以正常使用
