### ISSUE TITLE
protocol: vless/trojan

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#926]
go.Universe$proxyerror: v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: failed to parse to outbound detour config. > v2ray.com/core/infra/conf: unknown config id: vless 	at libv2ray.V2RayPoint.runLoop(Native Method) 

go.Universe$proxyerror: v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: failed to parse to outbound detour config. > v2ray.com/core/infra/conf: unknown config id: trojan	at libv2ray.V2RayPoint.runLoop(Native Method)

**Comment by ghost** [comment]
resolved
