### ISSUE TITLE
在Wear OS(Chinese)版本中运行出现错误

### ISSUE THREAD

**Issue by MuelNova** [2dust/v2rayNG#941]
V2RAY 在开启后被外部强行关闭

### 预期行为
打开V2RAY链接并工作正常

### 实际行为
V2RAY链接打开后，多次提示"已建立链接"，且无法关闭。

### 复现方法
1.使用 WEAR OS (我不确定是否为中国版特色） 给予 V2RAY 打开VPN的权限，链接即可

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
03-14 22:26:40.218 I/GoLog   ( 9219): [Warning] v2ray.com/core: V2Ray 4.32.1 started
03-14 22:26:40.309 D/com.v2ray.ang( 9219): [/data/app/com.v2ray.ang-6hrBTd49L5LEOX78r7E6Wg==/lib/arm/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
03-14 22:26:40.366 D/com.v2ray.ang( 9219): Process[pid=9247, hasExited=false]
03-14 22:26:40.366 D/com.v2ray.ang( 9219): /data/user/0/com.v2ray.ang/files/sock_path
03-14 22:26:40.410 I/tun2socks( 9247): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
03-14 22:26:40.533 D/com.v2ray.ang( 9219): sendFd tries: 0
03-14 22:26:40.573 I/tun2socks( 9247): NOTICE(tun2socks): entering event loop
03-14 22:26:40.617 D/AndroidRuntime( 9219): Shutting down VM
--------- beginning of crash
03-14 22:26:40.617 E/AndroidRuntime( 9219): FATAL EXCEPTION: main
03-14 22:26:40.617 E/AndroidRuntime( 9219): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 9219
03-14 22:26:40.617 E/AndroidRuntime( 9219): java.lang.RuntimeException: Unable to start receiver com.v2ray.ang.receiver.WidgetProvider: java.lang.NullPointerException: manager must not be null
03-14 22:26:40.617 E/AndroidRuntime( 9219): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3389)
03-14 22:26:40.617 E/AndroidRuntime( 9219): 	at android.app.ActivityThread.access$1200(ActivityThread.java:200)
03-14 22:26:40.617 E/AndroidRuntime( 9219): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1662)
03-14 22:26:40.617 E/AndroidRuntime( 9219): 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-14 22:26:40.617 E/AndroidRuntime( 9219): 	at android.os.Looper.loop(Looper.java:193)
03-14 22:26:40.617 E/AndroidRuntime( 9219): 	at android.app.ActivityThread.main(ActivityThread.java:6680)
03-14 22:26:40.617 E/AndroidRuntime( 9219): 	at java.lang.reflect.Method.invoke(Native Method)
03-14 22:26:40.617 E/AndroidRuntime( 9219): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-14 22:26:40.617 E/AndroidRuntime( 9219): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
03-14 22:26:40.617 E/AndroidRuntime( 9219): Caused by: java.lang.NullPointerException: manager must not be null
03-14 22:26:40.617 E/AndroidRuntime( 9219): 	at com.v2ray.ang.receiver.WidgetProvider.onReceive(WidgetProvider.kt:56)
03-14 22:26:40.617 E/AndroidRuntime( 9219): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3380)
03-14 22:26:40.617 E/AndroidRuntime( 9219): 	... 8 more
```
</details>

### 环境信息
Ticwatch Pro 3 
Wear os for Chinese

### 额外信息（可选）
同样的问题出现在手表设置代理服务器的情况
详见https://github.com/Jolanrensen/PermanentProxy-for-WearOS/issues/21

**Comment by MuelNova** [comment]
这是我的包列表
可能对判断错误有帮助
<details>
```
package:com.android.cts.priv.ctsshim
package:com.google.android.ext.services
package:com.android.providers.telephony
package:com.android.providers.calendar
package:com.android.providers.media
package:com.google.android.ext.shared
package:com.google.android.clockwork.flashlight
package:com.speedsoftware.rootexplorer
package:com.mobvoi.wear.bloodoxygen
package:com.mobvoi.wear.calculator.aw
package:com.android.mms.service
package:com.jeremysteckling.facerrel
package:com.google.android.wearable.setupwizard
package:com.android.providers.downloads
package:com.qualcomm.qti.telephonyservice
package:com.qualcomm.qti.auth.fidocryptoservice
package:com.v2ray.ang
package:cn.net.sunnysoft.scal
package:moe.shizuku.privileged.api
package:com.android.defcontainer
package:com.android.vending
package:com.mobvoi.wear.launcher.aw
package:com.google.android.wearable.batteryservices
package:com.google.android.wearable.overlay.home.mobvoi.tiles
package:com.sogou.map.android.maps
package:com.android.certinstaller
package:com.android.carrierconfig
package:com.google.android.marvin.talkback
package:android
package:com.mobvoi.wear.fitness.aw
package:com.google.android.clockwork.lesetup
package:com.sogou.ime.wear
package:com.google.android.apps.wearable.settings
package:com.android.nfc
package:com.android.backupconfirm
package:com.google.android.deskclock
package:com.mobvoi.wear.breath
package:com.mobvoi.ticwear.sidewearvoicesearch
package:org.codeaurora.ims
package:com.android.statementservice
package:com.qualcomm.qcrilmsgtunnel
package:com.android.providers.settings
package:com.google.android.apps.wearable.bluetooth
package:nu.back.button
package:com.jinheliu.knowledgeAll
package:com.mobvoi.wear.pay.aw
package:com.tencent.qqlite
package:com.google.android.apps.wearable.systemui
package:com.google.android.clockwork.gestures.tutorial
package:com.android.se
package:com.android.inputdevices
package:com.bilibili.comic
package:com.mobvoi.wear.account.aw
package:com.mobvoi.wear.sms.aw
package:cc.chenhe.weargallery
package:android.ext.shared
package:nl.jolanrensen.permanentproxy
package:com.android.server.telecom
package:com.android.keychain
package:com.mobvoi.wear.sleep.aw
package:com.google.android.packageinstaller
package:com.google.android.gms
package:com.google.android.gsf
package:android.ext.services
package:com.mobvoi.wear.pressure
package:rikka.appops
package:com.google.android.wearable.ambient
package:com.google.android.clockwork.remindersle
package:com.hippo.ehviewer
package:com.mobvoi.wear.heartrate.aw
package:com.android.managedprovisioning
package:com.mobvoi.wear.health.aw
package:cn.luern0313.wristbilibili
package:com.mobvoi.wear.recorder
package:com.google.android.apps.wearable.retailattractloop
package:com.google.android.apps.wearable.phone
package:com.ifreedomer.fuckmemory
package:com.mobvoi.wear.weather.aw
package:com.google.android.inputmethod.pinyin
package:com.mobvoi.ticwear.aw.appstore
package:com.google.android.wearable.app
package:com.android.cts.ctsshim
package:com.google.android.wearable.localedition.overlay.cmiit
package:cn.luern0313.wristvideoplayer
package:com.google.android.wearable.overlay.home.catshark
package:com.mobvoi.ticwear.noisedetect
package:com.google.android.apps.handwriting.ime
package:com.jinheliu.runningtext
package:com.mobvoi.wear.watchface.aw
package:com.android.phone
package:com.android.shell
package:com.android.wallpaperbackup
package:com.android.providers.blockednumber
package:com.android.providers.userdictionary
package:com.android.location.fused
package:com.mobvoi.wear.system.aw
package:com.spotify.lite
package:com.android.bluetooth
package:com.qualcomm.timeservice
package:com.qualcomm.atfwd
package:com.android.providers.contacts
package:com.stl.wristNotes
package:tv.danmaku.bili
package:com.google.android.wearable.frameworkpackagestubs
package:com.eg.android.AlipayGphone
package:com.mobvoi.ticwear.tts
```
</details>

**Comment by MuelNova** [comment]
```
package:com.android.cts.priv.ctsshim
package:com.google.android.ext.services
package:com.android.providers.telephony
package:com.android.providers.calendar
package:com.android.providers.media
package:com.google.android.ext.shared
package:com.google.android.clockwork.flashlight
package:com.speedsoftware.rootexplorer
package:com.mobvoi.wear.bloodoxygen
package:com.mobvoi.wear.calculator.aw
package:com.android.mms.service
package:com.jeremysteckling.facerrel
package:com.google.android.wearable.setupwizard
package:com.android.providers.downloads
package:com.qualcomm.qti.telephonyservice
package:com.qualcomm.qti.auth.fidocryptoservice
package:com.v2ray.ang
package:cn.net.sunnysoft.scal
package:moe.shizuku.privileged.api
package:com.android.defcontainer
package:com.android.vending
package:com.mobvoi.wear.launcher.aw
package:com.google.android.wearable.batteryservices
package:com.google.android.wearable.overlay.home.mobvoi.tiles
package:com.sogou.map.android.maps
package:com.android.certinstaller
package:com.android.carrierconfig
package:com.google.android.marvin.talkback
package:android
package:com.mobvoi.wear.fitness.aw
package:com.google.android.clockwork.lesetup
package:com.sogou.ime.wear
package:com.google.android.apps.wearable.settings
package:com.android.nfc
package:com.android.backupconfirm
package:com.google.android.deskclock
package:com.mobvoi.wear.breath
package:com.mobvoi.ticwear.sidewearvoicesearch
package:org.codeaurora.ims
package:com.android.statementservice
package:com.qualcomm.qcrilmsgtunnel
package:com.android.providers.settings
package:com.google.android.apps.wearable.bluetooth
package:nu.back.button
package:com.jinheliu.knowledgeAll
package:com.mobvoi.wear.pay.aw
package:com.tencent.qqlite
package:com.google.android.apps.wearable.systemui
package:com.google.android.clockwork.gestures.tutorial
package:com.android.se
package:com.android.inputdevices
package:com.bilibili.comic
package:com.mobvoi.wear.account.aw
package:com.mobvoi.wear.sms.aw
package:cc.chenhe.weargallery
package:android.ext.shared
package:nl.jolanrensen.permanentproxy
package:com.android.server.telecom
package:com.android.keychain
package:com.mobvoi.wear.sleep.aw
package:com.google.android.packageinstaller
package:com.google.android.gms
package:com.google.android.gsf
package:android.ext.services
package:com.mobvoi.wear.pressure
package:rikka.appops
package:com.google.android.wearable.ambient
package:com.google.android.clockwork.remindersle
package:com.hippo.ehviewer
package:com.mobvoi.wear.heartrate.aw
package:com.android.managedprovisioning
package:com.mobvoi.wear.health.aw
package:cn.luern0313.wristbilibili
package:com.mobvoi.wear.recorder
package:com.google.android.apps.wearable.retailattractloop
package:com.google.android.apps.wearable.phone
package:com.ifreedomer.fuckmemory
package:com.mobvoi.wear.weather.aw
package:com.google.android.inputmethod.pinyin
package:com.mobvoi.ticwear.aw.appstore
package:com.google.android.wearable.app
package:com.android.cts.ctsshim
package:com.google.android.wearable.localedition.overlay.cmiit
package:cn.luern0313.wristvideoplayer
package:com.google.android.wearable.overlay.home.catshark
package:com.mobvoi.ticwear.noisedetect
package:com.google.android.apps.handwriting.ime
package:com.jinheliu.runningtext
package:com.mobvoi.wear.watchface.aw
package:com.android.phone
package:com.android.shell
package:com.android.wallpaperbackup
package:com.android.providers.blockednumber
package:com.android.providers.userdictionary
package:com.android.location.fused
package:com.mobvoi.wear.system.aw
package:com.spotify.lite
package:com.android.bluetooth
package:com.qualcomm.timeservice
package:com.qualcomm.atfwd
package:com.android.providers.contacts
package:com.stl.wristNotes
package:tv.danmaku.bili
package:com.google.android.wearable.frameworkpackagestubs
package:com.eg.android.AlipayGphone
package:com.mobvoi.ticwear.tts
```

**Comment by yuhan6665** [comment]
Please try 1.5.16 or newer

**Comment by MuelNova** [comment]
> 请尝试1.5.16或更高版本

使用的正是1.5.16版本

**Comment by yuhan6665** [comment]
@the-25th-Nova 
`03-14 22:26:40.218 I/GoLog   ( 9219): [Warning] v2ray.com/core: V2Ray 4.32.1 started`
this log is older version, is it possible to upload a log from 1.5.16?

**Comment by MuelNova** [comment]
> @ the-25th-Nova
> `03-14 22:26:40.218 I/GoLog ( 9219): [Warning] v2ray.com/core: V2Ray 4.32.1 started`
> 该日志是较旧的版本，是否可以从1.5.16上传日志？

sorry I Download 1.5.16 but installed 1.4.16
I will try it and reply again
thx for your help

**Comment by MuelNova** [comment]
> @the-25th-Nova
> `03-14 22:26:40.218 I/GoLog ( 9219): [Warning] v2ray.com/core: V2Ray 4.32.1 started`
> this log is older version, is it possible to upload a log from 1.5.16?

It works!
I never have imagined this problem was caused by old version.
I appreciate your help.TY
