### ISSUE TITLE
最新版本1.6.0中，无法在开启本地DNS的情况下启动

### ISSUE THREAD

**Issue by yahaha-233** [2dust/v2rayNG#974]
### 预期行为
在开启本地DNS选项的情况下仍然能够启动服务。

### 实际行为
不开启本地DNS选项的情况下可以开启，但是开启本地DNS之后无法启动

### 复现方法
如前文所述

### 日志信息
报错如下
```
03-29 20:45:41.736 W/System.err(12249): java.lang.NumberFormatException: For input string: ""
03-29 20:45:41.736 W/System.err(12249):  at java.lang.Integer.parseInt(Integer.java:627)
03-29 20:45:41.736 W/System.err(12249):  at java.lang.Integer.parseInt(Integer.java:650)
03-29 20:45:41.736 W/System.err(12249):  at com.v2ray.ang.util.Utils.parseInt(Utils.kt:61)
03-29 20:45:41.736 W/System.err(12249):  at com.v2ray.ang.util.V2rayConfigUtil.customLocalDns(V2rayConfigUtil.kt:285)
03-29 20:45:41.736 W/System.err(12249):  at com.v2ray.ang.util.V2rayConfigUtil.getV2rayNonCustomConfig(V2rayConfigUtil.kt:70)
03-29 20:45:41.736 W/System.err(12249):  at com.v2ray.ang.util.V2rayConfigUtil.getV2rayConfig(V2rayConfigUtil.kt:38)
03-29 20:45:41.736 W/System.err(12249):  at com.v2ray.ang.service.V2RayServiceManager.startV2rayPoint(V2RayServiceManager.kt:126)
03-29 20:45:41.736 W/System.err(12249):  at com.v2ray.ang.service.V2RayVpnService.onStartCommand(V2RayVpnService.kt:251)
03-29 20:45:41.736 W/System.err(12249):  at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3739)
03-29 20:45:41.736 W/System.err(12249):  at android.app.ActivityThread.access$1700(ActivityThread.java:202)
03-29 20:45:41.736 W/System.err(12249):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1712)
03-29 20:45:41.736 W/System.err(12249):  at android.os.Handler.dispatchMessage(Handler.java:106)
03-29 20:45:41.736 W/System.err(12249):  at android.os.Looper.loop(Looper.java:207)
03-29 20:45:41.736 W/System.err(12249):  at android.app.ActivityThread.main(ActivityThread.java:6878)
03-29 20:45:41.736 W/System.err(12249):  at java.lang.reflect.Method.invoke(Native Method)
03-29 20:45:41.736 W/System.err(12249):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
03-29 20:45:41.736 W/System.err(12249):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

### 环境信息

软件版本1.6.0，系统Android9.0.

**Comment by yuhan6665** [comment]
感谢反馈，会尽快修复，能否看看本地DNS的具体配置（如果有敏感信息记得打码）

**Comment by yahaha-233** [comment]
> 感谢反馈，会尽快修复，能否看看本地DNS的具体配置（如果有敏感信息记得打码）

就是在UI中直接填写的DNS设置，UDP和DoH都尝试了，都是无法启动。

**Comment by l123456789jy** [comment]
> > 感谢反馈，会尽快修复，能否看看本地DNS的具体配置（如果有敏感信息记得打码）
> 
> 就是在UI中直接填写的DNS设置，UDP和DoH都尝试了，都是无法启动。

卸载在安装就可以了

**Comment by yahaha-233** [comment]
> > > 感谢反馈，会尽快修复，能否看看本地DNS的具体配置（如果有敏感信息记得打码）
> > 
> > 
> > 就是在UI中直接填写的DNS设置，UDP和DoH都尝试了，都是无法启动。
> 
> 卸载在安装就可以了

重装可解决。
